#!/bin/bash

GITPATH=${GITPATH:=/var/spool/git}

REPO=${1}
GITUSER=Distrotech
REMOTE=${2}

##create a bare clone
RPATH=${GITPATH}/${REPO}.git
if [ ! -d ${RPATH} ];then
  mkdir ${RPATH}
fi;
cd ${RPATH}

if [ ! -e config ] && [ ${REMOTE} ];then
  git clone --mirror "bzr::${REMOTE}" .
  git config daemon.uploadarch true
  git repack -adF
fi;
