#!/bin/bash

GITPATH=${GITPATH:=/var/spool/git}

if [ ! -d ${GITPATH}/${1}.git ];then
  exit
fi;

cd ${GITPATH}/${1}.git
if [ ! -d bzr ] && [ ! -d hg ] && [ ! -d svn ];then
  exit
fi;
git repack -adF
