#!/bin/bash

URL=https://github.com/distrotech/${1}

if [ -d /var/spool/git/${1}.git  ];then
  git clone file:////var/spool/git/${1}.git
 else
  git clone ${URL}
fi

cd ${1}
git remote set-url origin ${URL}.git
git checkout distrotech-${1}
