#!/bin/bash

GITPATH=${GITPATH:=/var/spool/git}

URL=https://github.com/distrotech/${1}

if [ -d ${GITPATH}/${1}.git  ];then
  git clone file://${GITPATH}/${1}.git
 else
  git clone ${URL}
fi

cd ${1}
git remote set-url origin ${URL}.git
git checkout distrotech-${1}
