#!/bin/bash

REPO=${1}
GITUSER=Distrotech
REMOTE=${2}
GITPATH=${GITPATH:=/var/spool/git}
SVNPATH=${SVNPATH:=/usr/src/svngit}

export GIT_SSL_NO_VERIFY=true

mkdir -p ${SVNPATH}/${REPO}
cd ${SVNPATH}/${REPO}

git svn init -t tags -b branches -T trunk ${2}
git svn fetch

git branch -r |grep -vE "^[\ ]+tags" |awk '{printf "if [ ! -e refs/heads/%s ];then git branch %s remotes/%s;fi\n",$1,$1,$1}' |sh

exit

##create a bare clone
RPATH=${GITPATH}/${REPO}.git
if [ ! -d ${RPATH} ];then
  mkdir ${RPATH}
fi;
cd ${RPATH}

#rsync -avP svngit/bakefile/.git/ ${GITPATH}/bakefile.git
#sed -i -e "s/bare = false/bare = true/" ${GITPATH}/bakefile.git/config
