#!/bin/bash

if [ -e ~/.distrotech_build ];then
  . ~/.distrotech_build
 else
  GITURL="git://github.com/Distrotech";
  DISTDIR="/dist";
fi;
export GITURL DISTDIR

if [ ! -d ${DISTDIR}/.git ];then
  if [ ! -d ${DISTDIR} ];then
    mkdir ${DISTDIR}
  fi;
  git clone ${GITURL}/buildscripts.git ${DISTDIR}/
 else
  (cd ${DISTDIR}
  git pull)
fi;

${DISTDIR}/scripts/build $@
