#!/bin/bash

export PYTHONHOME=${ARCHROOT}/${1}/usr
${ARCHROOT}/${1}/usr/bin/python2.7 configure.py --confirm-license

sed -i -e "s/.*\-strip.*//" Makefile
make ${MAKE_J}
make INSTALL_ROOT=${3} install
