#!/bin/bash

make realclean
rm Policy.sh config.sh > /dev/null 2>&1

./Configure -e -d -s -Dusethreads -Dprefix=/usr -Dcc=/usr/bin/${HOST}-gcc -A append:cc=" --sysroot=${SYSROOT} -fPIC" \
            -A libpth="/${B_LIBDIRS} /usr/${B_LIBDIRS} ${X11DIR}/${B_LIBDIRS}" \
            -Dlocincpth="/usr/include /usr/X11R7/include" -Darchname=${HOST} -Duselargefiles

make ${MAKE_J} || make ${MAKE_J} || make || exit 1
if [ "${SYSROOT}" ];then
  make DESTDIR=${SYSROOT} install
 else
  make install
fi;

if [ -x ${SYSROOT}/usr/bin/perl ];then
  eval `chroot ${SYSROOT} /usr/bin/perl -V:privlib -V:archlib -V:sitearch -V:sitelib`
  export PERL5LIB=${SYSROOT}/${privlib}:${SYSROOT}/${archlib}:${SYSROOT}/${sitearch}:${SYSROOT}/${sitelib}
fi;

if [ ! -e cpan/Pod-LaTeX/blib/script/pod2latex ] && [ -e cpan/Pod-LaTeX/pod2latex ];then
  cp cpan/Pod-LaTeX/pod2latex cpan/Pod-LaTeX/blib/script/pod2latex
fi;

if [ ! -e cpan/podlators/blib/script/pod2man ];then
  (cd cpan/podlators/;../../perl Makefile.PL;make)
fi;

if [ ! -e cpan/Pod-Parser/blib/script/pod2usage ];then
  (cd cpan/Pod-Parser/;../../perl Makefile.PL;make)
fi;

make DESTDIR=${3} install
