#!/bin/bash

XULVER="30.0";

unset LD CC CXX AS

export CFLAGS="-I=/usr/include/gtk-2.0 -I=/opt/Xorg/include -I=/usr/include/gdk-pixbuf-2.0 -I=/usr/include/xulrunner-${XULVER}";
export CXXFLAGS=${CFLAGS}
export LDFLAGS="-L=/usr/${C_LIBDIRS} -L=/opt/Xorg/${B_LIBDIRS} -L=/usr/${C_LIBDIRS}/nss"

CWD=$(pwd)
(
cat <<EOF
mk_add_options MOZ_MAKE_FLAGS="${MAKE_J} VERBOSE=1"
mk_add_options AUTOCLOBBER=1
#ac_add_options --enable-optimize --disable-debug
#ac_add_options --disable-tests

mk_add_options MOZ_OBJDIR=${CWD}/build-${1}
ac_add_options --disable-crashreporter
ac_add_options --disable-installer
ac_add_options --disable-updater
ac_add_options --x-includes=/usr/Xorg/include
ac_add_options --x-libraries=/opt/Xorg/lib64
ac_add_options --with-branding=browser/branding/official/
ac_add_options --with-system-nspr
ac_add_options --with-system-nss
ac_add_options --enable-system-hunspell
ac_add_options --with-system-libevent
ac_add_options --with-system-zlib
ac_add_options --with-system-bz2
ac_add_options --enable-system-ffi
ac_add_options --enable-system-pixman
ac_add_options --with-system-libvpx
ac_add_options --disable-libjpeg-turbo
ac_add_options --enable-default-toolkit=cairo-gtk2
ac_add_options --with-pthreads
ac_add_options --target=${HOST}
ac_add_options --with-system-cairo
ac_add_options --enable-safe-browsing
ac_add_options --enable-url-classifier
ac_add_options --with-system-icu
ac_add_options --enable-gio
ac_add_options --with-libxul-sdk=/usr/${C_LIBDIRS}/xulrunner-devel-${XULVER}
ac_add_options --with-system-libxul

ac_add_options --prefix=/usr
ac_add_options --libdir=/usr/${C_LIBDIRS}
ac_add_options --mandir=/usr/share/man
ac_add_options --localstatedir=/var
ac_add_options --infodir=/usr/share/info

EOF
) > .mozconfig

if [ ! -d /root/.mozbuild ];then
  mkdir /root/.mozbuild
fi;
MOZBUILD_STATE_PATH=/root/.mozbuild ./mach build

make -C build-${1} DESTDIR=${3} install && \
ln -sr ${3}/usr/${C_LIBDIRS}/xulrunner-${XULVER} ${3}/usr/${C_LIBDIRS}/firefox-${XULVER}/xulrunner && \
rm -rf build-${1}
