#!/bin/bash

unset CFLAGS CXXFLAGS CC

ARCHT="x86_64-linux-gnu x86_64-linux-gnux32 i686-linux-gnu \
       ppc-linux-gnu ppc64-linux-gnu arm-linux-gnueabi \
       aarch64-linux-gnu mips64-linux-gnuabi64 mips-linux-gnu \
       armv6-linux-gnueabi armv5-linux-gnueabi";

for acpp in ${ARCHT};do
  touch /usr/bin/${acpp}-g++
done

cp tools/build/example/user-config.jam ~/
sh ./bootstrap.sh

case ${1} in
  x86_32)./b2 abi=x32 gcc-${1};;
  *)./b2 gcc-${1};;
esac;

if true;then
  if [ ! -d ${3}/usr/${B_LIBDIRS} ];then
    mkdir -p ${3}/usr/${B_LIBDIRS}
  fi;
  if [ ! -d ${3}/usr/include ];then
    mkdir -p ${3}/usr/include
  fi;
  rsync -avP stage/lib/ ${3}/usr/${C_LIBDIRS}/
  rsync -avP boost ${3}/usr/include/
fi;

if [ -e ~/user-config.jam ];then
  rm ~/user-config.jam
fi

for acpp in ${ARCHT};do
  if [ ! -s /usr/bin/${acpp}-g++ ];then
    rm /usr/bin/${acpp}-g++
  fi;
done;
