#!/bin/bash

case ${1} in
  arm)TYPE=linux-armv4
      SARCH=arm;;
  arm64)TYPE=linux-aarch64
      SARCH=arm64;;
  i686)TYPE=linux-elf
      SARCH=i386;;
  x86_32)TYPE=linux-x32
      SARCH=x86_64;;
  mips)TYPE=linux-mips
       SARCH=mips;;
  mips64)TYPE=linux-mips64
       SARCH=mips;;
  ppc)TYPE=linux-ppc
       SARCH=powerpc;;
  ppc64)TYPE=linux-ppc64
       SARCH=powerpc;;
  x86_64)TYPE=linux-x86_64
      SARCH=${1};;
  win32|cyg32)TYPE=mingw
      SARCH=${1};;
  win64|cyg64)TYPE=mingw64
      SARCH=${1};;
esac;

if [ "${1}" == "${NARCH}" ] && [ ! -d /build/${1} ];then
  INCDIR=${ARCHPREFIX}/include
 else
  INCDIR=${ARCHROOT}/${1}${ARCHPREFIX}/include
fi;

make clean
rm Makefile Makefile.bak
SYSROOT=`${2}-gcc -print-sysroot`
./Configure --prefix=${ARCHPREFIX} --openssldir=/etc/openssl shared zlib-dynamic ${TYPE}
make LDFLAGS="-L${SYSROOT}/${ARCHPREFIX}/${C_LIBDIRS}" AR="${AR} r" RANLIB=${RANLIB} \
  CC=${HOST}-gcc CROSS_COMPILE=${HOST}- ARCH=${SARCH} INCLUDEDIR=${INCDIR} INSTALL_PREFIX=${3} \
  MANDIR=${ARCHPREFIX}/share/man all install || exit 1

rm -rf ${3}/etc/openssl/certs
ln -s ../ssl/certs ${3}/etc/openssl/certs
