#!/bin/bash

PKG=$( basename `pwd` )

unset CFLAGS CPPFLAGS LDFLAGS

for ARCH in arm x86_64 i686;do
  if [ -d /dist/${ARCH} ];then
    if [ -d /dist/${ARCH}/${PKG} ];then
      rm -rf /dist/${ARCH}/${PKG}
    fi;
    mkdir -p /dist/${ARCH}/${PKG}
    (cat <<EOF
#!/bin/bash
   
$0 ${ARCH} "$@"
EOF
) > /dist/${ARCH}/${PKG}.conf
    chmod 750 /dist/${ARCH}/${PKG}.conf
  fi;
done;

for barch in i686 arm x86_64;do
  if [ "${barch}" == "arm" ];then
    HOST=${barch}-embed-linux-gnueabi
   else
    HOST=${barch}-pc-linux-gnu
  fi;
  make clean
  SYSROOT=`${HOST}-gcc -print-sysroot`
  export CFLAGS="-I/build/${barch}/usr/include"
  make V=1 LDFLAGS="-L${SYSROOT}/usr/lib" AR=${HOST}-ar RANLIB=${HOST}-ranlib LD=${HOST}-ld \
    CXX=${HOST}-g++ CC=${HOST}-gcc DESTDIR=/dist/${barch}/${PKG} all install
  rsync -avP /dist/${barch}/${PKG}/ /build/${barch}/
done;
