#!/bin/bash

if [ ! "${1}" ];then
  echo "Arch needed";
  exit
fi;

if [ ! -d /dist/status/${1} ];then
  mkdir -p /dist/status/${1}
fi;

if [ -d /dist/status/${1}/done ];then
  rm /dist/status/${1}/done/*
fi;

if [ -d /dist/status/${1}/fail ];then
  rm /dist/status/${1}/fail/*
fi;

touch /dist/status/${1}/newbuild

find /build/${1}/etc /build/${1}/root/ ! -newer /dist/status/${1}/newbuild  |awk '{printf "touch %s\n",$1}' |sh

touch /dist/status/${1}/newbuild2

for pkg in glibc libtool libiconv gmp mpfr mpc ppl cloog isl gcc binutils;do
  /dist/scripts/build ${1} distclean ${pkg} || break
  touch /dist/status/${1}/done/${pkg}
done

if [ -e /dist/status/${1}/done/binutils ];then
  /dist/scripts/buildall ${1} distclean
fi;
