#!/bin/bash

SVNIP=192.168.25.1
SVNBASE=http://${SVNIP}/svn

#Setup layout path
SRCDIR=/usr/src
DISTDIR=/dist
STATDIR=${DISTDIR}/status
DEFDIR=${DISTDIR}/def
PKGDISTDIR=${DISTDIR}/pkg
TOOLPKG=${PKGDISTDIR}/build
TOOLDIR=${DISTDIR}/cross
BASEROOT=${DISTDIR}/root
SCRIPTDIR=${DISTDIR}/scripts
PKGBUILDDIR=${DISTDIR}/build
ARCHROOT=/build
SVNURL=${SVNBASE}/distro/
SVNUPDATE=0;
AMDEF="1.11";

#Multiarch Definitions
MARCH_x86_64="x86_32|i[3-6]86|x86_64"
MARCH_x86_32=${MARCH_x86_64}

#Parse cmdline opts
#Adding a arch here may require you adding tupple/kernel arch/libdirs and MLOPTS bellow in arch_config
ALLARCHLIST="i686 arm x86_64 x86_32 mips mips64 powerpc powerpc64";
ARCHMPAT=${ALLARCHLIST// /|}
ALLARCH="0";

ARCHLIST="";
CLEANOPT="";
MAKE_J="-j6"

while (( $# > 1 ));do
  case ${1} in
    clean|distclean)CLEANOPT=${1};;
    noclean)NOCLEAN=1;;
    -)shift;
      break;;
    buildall)ALLARCH="1";;
    *)if [[ ${1} =~ ${ARCHMPAT} ]] && [ -d ${ARCHROOT}/${1} ];then
        ARCHLIST="${ARCHLIST} ${1}"
      fi;;
  esac;
  shift;
done;

#Is last man standing a arch ??
if [ "${1}" ] && [[ ${1} =~ ${ARCHMPAT} ]];then
  ARCHLIST="${ARCHLIST} ${1}"
  shift;
 elif [ "${1}" ] && [ "${1}" == "buildall" ];then
  ARCHLIST=${ALLARCHLIST}
 elif [ "${ALLARCH}" == "1" ];then
  ARCHLIST=${ALLARCHLIST}
fi;

ulimit -s 16384

#Set the arch based on uname -m this is not able to determine multi/sub arches
export NARCH=${NARCH:=$( uname -m )}

#Native if not specified
if [ ! "${ARCHLIST}" ];then
  ARCHLIST=${NARCH}
fi;

unset CFLAGS LDFLAGS CPPFLAGS

arch_config() {
  #Set build tupple
  case ${1} in
    arm64)TUPPLE=aarch64-linux-gnu;;
    arm)TUPPLE=arm-linux-gnueabi;;
    mips64)TUPPLE=mips64-linux-gnuabi64;;
    x86_32)TUPPLE=x86_64-linux-gnux32;;
    *)TUPPLE=${1}-linux-gnu;;
  esac;

  #Set Libdir
  case ${1} in
    x86_32)SETLIBDIR="libx32";;
    arm64)SETLIBDIR="lib";;
    *64)SETLIBDIR="lib64";;
    *)SETLIBDIR="lib";;
  esac;

  #Determine kernel arch
  case ${1} in
    x86_*|i[3-6]86)LINARCH="x86";;
    arm64)LINARCH=arm64;;
    *64)LINARCH=${1::-2};;
    *)LINARCH=${1};
  esac;
}

#Check arch export common env variables
check_create_arch() {
  #Set tupple  
  arch_config ${1}
  HOST=${TUPPLE}
  KARCH=${LINARCH}
  B_LIBDIRS=${SETLIBDIR}
  
  unset TUPPLE SETLIBDIR LINARCH

  case ${1} in
    arm|arm64)QCPU=arm;;
    mips|mips64)QCPU=mips;;
    powerpc)QCPU=ppc;;
    powerpc64)QCPU=ppc64;;
  esac;

  #Multi arch opts
  MLOPT="";
  MLLDOPT="";
  MLASOPT="";
  if [ "${NARCH}" == "x86_64" ];then
    case ${1} in
      i686)MLOPT=" -m32"
           MLLDOPT=" -m elf_i386";
           MLASOPT=" --32";;
      x86_32)MLOPT=" -mx32";
             MLLDOPT=" -m elf32_x86_64";
             MLASOPT=" --x32";;
      x86_64)MLOPT=" -m64";
             MLLDOPT=" -m elf_x86_64";
             MLASOPT=" --64";;
    esac;
    if [ "${MLOPT}" ];then
      MLHOST=${BUILD};
     else
      MLHOST=${HOST};
    fi;
   else
    MLHOST=${HOST};
  fi;

  export B_LIBDIRS HOST KARCH QCPU MLHOST MLASOPT MLLDOPT MLOPT

  HDIR=${BASEROOT}/${1}
  if [ ! -d ${HDIR} ];then
    mkdir -p ${HDIR}/usr/include
  fi;

  if [ -d ${SRCDIR}/linux/usr/include/linux ];then
    if [ ! -d ${HDIR}/usr/include ] || [ ! -f ${TOOLPKG}/${1}/kernel-headers.tar.xz ] || \
       [ ${SRCDIR}/linux/usr/include/linux -nt ${HDIR}/usr/include/linux ];then
      
      rsync -aP --include=asm-${KARCH} --include=asm-generic --exclude=.install --exclude=..install.cmd \
                --exclude=asm* ${SRCDIR}/linux/usr/include/ ${HDIR}/usr/include/
      if [ -e ${HDIR}/usr/include/asm ] && [ ! -h ${HDIR}/usr/include/asm ];then
        rm -rf ${HDIR}/usr/include/asm
      fi;
      if [ ! -e ${HDIR}/usr/include/asm ];then
        ln -s asm-${KARCH} ${HDIR}/usr/include/asm
      fi;
      if [ -d ${ARCHROOT}/${1} ] && [ ! -h ${ARCHROOT}/${1} ];then
        if [ ! -d ${ARCHROOT}/${1}/usr/include ];then
          mkdir -p ${ARCHROOT}/${1}/usr/include
        fi;
        rsync -avP ${HDIR}/usr/include/ ${ARCHROOT}/${1}/usr/include/ >/dev/null
      fi;

      (cd ${SRCDIR}/linux
       if [ ! -d ${TOOLPKG}/${1}/ ];then
         mkdir -p ${TOOLPKG}/${1}
       fi;
      find . ! -regex '.*\.install$' -and ! -regex '.*\.\.install.cmd$'  -and ! -regex '.*\.check$' -and ! -regex \
             '.*\.check.cmd$' -and ! -regex '\.\/usr\/include\/asm-.*' -and -regex '\.\/usr\/include\/.*' -or -regex \
             "\.\/usr\/include\/asm-${KARCH}\/.*\.h" |cpio -o -H tar |xz -9 > ${TOOLPKG}/${1}/kernel-headers.tar.xz)
    fi;
  fi;

  if [ "${1}" == "${NARCH}" ];then
    rsync -avPR /usr/include/gnu/stubs-*.h ${HDIR}/
   elif [ -d ${ARCHROOT}/${1}/usr/include/gnu ];then
    rsync -avPR ${ARCHROOT}/usr/include/gnu/stubs-*.h ${HDIR}/
  fi; 

  #Sync root too arch if no includes
  if [ -d ${ARCHROOT}/${1} ] && [ ! -d ${ARCHROOT}/${1}/usr/include ];then
    mkdir -p ${ARCHROOT}/${1}/usr/include
    rsync -aP ${HDIR}/usr/include/ ${ARCHROOT}/${1}/usr/include/
  fi;
}

svn_load_pkg() {
  if [ "${2}" ];then
    if [ ! -d ${SRCDIR}/${1} ];then
      svn co --depth=empty ${SVNURL}/${1} ${SRCDIR}/${1} || return 1
    fi;
    PKGSVNDIR=${1}/${2}
   else
    PKGSVNDIR=${1}
  fi;
  if [ ! -d ${SRCDIR}/${PKGSVNDIR} ];then
    svn co ${SVNURL}/${PKGSVNDIR} ${SRCDIR}/${PKGSVNDIR} || return 1
    if [ "${NONULLCONF}" ] && [ "${NONULLCONF}" == "1" ];then
      return 0;
    fi;
    #some packages are retards null config them
    if [ -e ${SRCDIR}/${PKGSVNDIR}/configure.ac ] || [ -e ${SRCDIR}/${PKGSVNDIR}/configure.in ];then
      if [ "${SRCDIR}" ] && [ "${PKGSVNDIR}" ] && [ -d ${SRCDIR}/${PKGSVNDIR} ];then
        (cd ${SRCDIR}/${PKGSVNDIR}
         sh ./configure;
         make distclean || rm -rf ${SRCDIR}/${PKGSVNDIR}/*
         svn up)
      fi
    fi;
   elif [ "${SVNUPDATE}" == "1" ];then
    svn up ${SRCDIR}/${PKGSVNDIR}
  fi;
}

check_package() {
  #Help out on bad project XXXX SVN check/fetch
  if [ ! -e ${DEFDIR}/${1} ];then
    (cat <<EOF

Missing build def file for ${1}

This file is a file that is read with eval and contains the following vars

PREFIX: Install prefix
VERSION: version number to use optional
VERSEP: seperator used to determine source directory ${SRCDIR}/<project>[\${VERSEP}\${VERSION}]
CONFOPT: Options [excluding --prefix / --host / --build] passed to configure 
ARCH: list of arch to build for
ARCHOPT: Array of aditional options passed to configure per arch [1,2,...]
CFGPTH: Change to this dir before running configure
BUILDDIR: Use build dirs assumed to be 1 if not set too 0
CFGBIN: Prefix to configure bin file
ADDPATH: Add to PATH
ADDCFLAG: Add to CFLAGS
ADDLDFLAG: Add to LDFLAGS
MAKEOPTS: Additional opts passed to Make
MAKETARGETS: Additional Targets passed to make
MAKEITARGETS: Additional Targets passed to make with install
STDOPTS: use these not the builtin configure options 
ADDFILTER: also add these files to filter
SYSCONFPRE: prefix sysconfdir
EXTRALIBS: Add to the linked LIBS list
NOMAKEFLAGS: Dont pass CFLAGS/LDFLAGS To make
CANBUILD: Space seperated lists of arch to build for
EOF
    )
    return 255
  fi;
}

strip_path() {
  path=${1}

  if [ ! -d ${path}/.dbg ];then
    mkdir ${path}/.dbg
  fi;

  for file in `ls ${path}`;do
    if [ ! -s ${path}/${file} ] || [ -h ${path}/${file} ];then
      continue
    fi;
    if ${OBJCOPY} --only-keep-debug ${path}/${file} ${path}/.dbg/${file};then
      ${OBJCOPY} --strip-debug ${path}/${file}
      ${OBJCOPY} --add-gnu-debuglink=${path}/.dbg/${file} ${path}/${file}
    fi;
  done;
}

strip_rootdir() {
  for extrapath in ${1} ${1}/usr `ls -d ${1}/opt/* 2>/dev/null` ${1}/usr/X11R7;do
    for append in bin sbin lib libx32 lib64;do
      if [ -d ${extrapath}/${append} ];then
        strip_path ${extrapath}/${append} 2>/dev/null
      fi;
    done;
  done
}

tar_package() {
  strip_rootdir ${1}

  if [ ! -d ${2}/${3} ];then
    mkdir -p ${2}/${3}
  fi;

  (cd ${1}
  mylang="en";
  pkgpre=${2}/${3}/${3}


  manpages=".*\/share\/man\/.*";
  infopages=".*\/share\/info/.*";
  sharedoc=".*\/share\/doc\/.*";
  dbginfo=".*\/\.dbg"
  allloc="\.\/usr\/share\/locale\/.*";
  myloc="\.\/usr\/share\/locale\/${mylang}.*";

  find . ! -regex "\.\/include\/.*" -and ! -regex "\.\/usr\/include\/.*" -and ! -regex "\.\/etc\/.*" \
         ! -regex "\.\/opt\/[a-zA-Z0-9\-_]+\/include\/.*" -and ! -regex "\.\/usr\/X11R7\/include\/.*" -and \
         ! -regex ".*\/${B_LIBDIRS}\/.*" -and ! -regex "\.\/etc" -and \
         ! -regex "${dbginfo}" -and ! -regex "${dbginfo}\/.*" -and ! -regex "${sharedoc}" -and \
         ! -regex "${manpages}" -and ! -regex "${infopages}" -and ! -regex "\.\/usr\/${B_LIBDIRS}\/locale\/.*" \
         ! -regex ".*\/include" -and ! -regex ".*\/share\/doc" -and ! -regex ".*\/share\/man" -and \
         ! -regex ".*\/share\/info" -and ! -regex "${allloc}" -or -regex "${myloc}" |\
       cpio -ov -H tar |xz -9 > ${pkgpre}.tar.xz

  #try limit it to pkgs with include dirs / libdirs this is not fool proof ie /opt/....
  if [ -d include ] || [ -d usr/include ] || [ -d usr/X11R7/include ] || [ -d opt ] || \
     [ -d ${B_LIBDIRS} ] || [ -d usr/${B_LIBDIRS} ] || [ -d usr/X11R7/${B_LIBDIRS} ];then
    find . ! -regex ".*\/${B_LIBDIRS}\/.*\.a" -and ! -regex ".*\/${B_LIBDIRS}\/.*\.la" -and \
           ! -regex "${dbginfo}\/.*" -and ! -regex "${dbginfo}\/.*" -and \
           ! -regex "\.\/usr\/${B_LIBDIRS}\/locale\/.*" -and -regex ".*\/${B_LIBDIRS}\/.*" |\
         cpio -ov -H tar |xz -9 > ${pkgpre}-libs.tar.xz
    find . -regex "\.\/include\/.*" -or -regex "\.\/usr\/include\/.*" -or \
           -regex "\.\/opt\/[a-zA-Z0-9\-_]+\/include\/.*" -or -regex "\.\/usr\/X11R7\/include\/.*" \
           -or -regex ".*\/${B_LIBDIRS}\/.*\.a" -or -regex ".*\/${B_LIBDIRS}\/.*\.la" |\
         cpio -ov -H tar |xz -9 > ${pkgpre}-dev.tar.xz
  fi;

  find . -regex "${dbginfo}\/.*" -and ! -regex ".*\/${B_LIBDIRS}\/\.dbg\/.*\.a" |\
         cpio -ov -H tar |xz -9 > ${pkgpre}-dbg.tar.xz

  if [ -d usr/share/locale ] || [ -d usr/${B_LIBDIRS}/locale ];then
    find . -regex "${allloc}" -and ! -regex "${myloc}" -or -regex "\.\/usr\/${B_LIBDIRS}\/locale\/.*" |\
         cpio -ov -H tar |xz -9 > ${pkgpre}-locale.tar.xz
  fi;

  if [ -d usr/share/man ] || [ -d usr/share/doc ] || [ -d usr/share/info ] || \
     [ -d usr/X11R7/share/man ] || [ -d usr/X11R7/share/doc ] || [ -d usr/X11R7/share/info ] || \
     [ -d share/man ] || [ -d share/doc ] || [ -d share/info ] || [ -d opt ];then
    find . -regex "${sharedoc}" -or -regex "${manpages}" -or -regex "${infopages}" |\
         cpio -ov -H tar |xz -9 > ${pkgpre}-doc.tar.xz
  fi;

  if [ -d etc ];then 
    find . -regex "\.\/etc\/.*" |\
         cpio -ov -H tar |xz -9 > ${pkgpre}-conf.tar.xz
  fi;)
}

sysroot_fixup() {
  if [ "${SYSROOTFIXUP}" == "1" ];then
    #Replace all libtools with the "sysroot" version
    for ltool in `find . -name libtool`;do
      if [ -x ${ltool} ];then
        rm ${ltool}
        if [ -d ${ARCHROOT}/${1} ] && [ ! -h ${ARCHROOT}/${1} ];then
          cp ${ARCHROOT}/${1}/usr/bin/libtool ${ltool}
         else
          cp /usr/bin/libtool ${ltool}
        fi;
      fi;
    done

    #Filter all -L / -I bits and rebase to sysroot
    for mfile in `find . -name Makefile` ${ADDFILTER};do
      sed -i -e "s/\-L\/\//\-L\//g" -e "s/\-L\(\/usr\/\)li[bx3246]\+/\-L=\1${B_LIBDIRS}/g" \
             -e "s/\-L\(\/usr\/X11R7\/\)li[bx3246]\+/\-L=\1${B_LIBDIRS}/g" \
             -e "s/\-L\(\/\)li[bx3246]\+/\-L=\1${B_LIBDIRS}/g" \
             -e "s/\-I\//\-I=\//g" $mfile
    done
  fi;
}

make_cc_destdir() {
  if [ "${LDISCC}" == "1" ];then
    export LD="${CC} ${CC_SYSROOT}"
   else
    export LD="${MLHOST}-ld --sysroot=${SYSROOT}/${MLLDOPT} --rpath-link=${RPATH_LINK}"
  fi;

  if [ "${NOMAKEFLAGS}" == "1" ];then
    unset CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
    /usr/bin/make ${MAKE_J} V=1 AR=${AR} RANLIB=${RANLIB} LD="${LD}" SYSROOT=${SYSROOT} \
      CXX="${CXX} ${CC_SYSROOT}" CC="${CC} $CC_SYSROOT}" ${MAKEOPTS} \
      ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS}
    RES=$?
    if [ ${RES} != 0 ] && [ "${MAKE_J}" ];then
      /usr/bin/make V=1 AR=${AR} RANLIB=${RANLIB} LD="${LD}" SYSROOT=${SYSROOT} \
        CXX="${CXX} ${CC_SYSROOT}" CC="${CC} $CC_SYSROOT}" ${MAKEOPTS} \
        ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} || return 1
     elif [ ${RES} != 0 ];then
      return 1
    fi;
    /usr/bin/make V=1 AR=${AR} RANLIB=${RANLIB} LD="${LD}" SYSROOT=${SYSROOT} \
        CXX="${CXX} ${CC_SYSROOT}" CC="${CC} $CC_SYSROOT}" ${ARCHMOPT} DESTDIR=${DIST_ROOT} \
        ${MAKEOPTS} ${ARCHMOPT} ${MAKEITARGETS} install  || return 1
   else
    /usr/bin/make ${MAKE_J} V=1 LDFLAGS="${LDFLAGS}" CFLAGS="${CFLAGS}" AR=${AR} RANLIB=${RANLIB} LD="${LD}" \
      CXX="${CXX} ${CC_SYSROOT}" CC="${CC} ${CC_SYSROOT}" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} || return 1
      /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install || return 1
    RES=$?
    if [ ${RES} != 0 ] && [ "${MAKE_J}" ];then
      /usr/bin/make V=1 LDFLAGS="${LDFLAGS}" CFLAGS="${CFLAGS}" AR=${AR} RANLIB=${RANLIB} LD="${LD}" \
        CXX="${CXX} ${CC_SYSROOT}" CC="${CC} ${CC_SYSROOT}" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} || return 1
      /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEITARGETS} install || return 1
     elif [ ${RES} != 0 ];then
      return 1
    fi;
  fi;
}

imake_cross_build() {
  CC_TMP=${CC}
  unset CC
  /usr/bin/make distclean
  xmkmf -a || return 1

  #Postconfig hook
  if [ -e ${SRCDIR}/${PSOURCEDIR}/.build-info/post-config ];then
    sh ${SRCDIR}/${PSOURCEDIR}/.build-info/post-config ${2} ${SRCDIR}/${PSOURCEDIR} ${DIST_ROOT}
  fi;

  sysroot_fixup ${1}

  /usr/bin/make V=1 CXX="${CXX} ${CC_SYSROOT}" CC="${CC_TMP} ${CC_SYSROOT}" SHLIBDIR=/usr/X11R7/${B_LIBDIRS} \
       LOCAL_LDFLAGS="-L${SYSROOT}/usr/X11R7/${B_LIBDIRS}" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} || return 1
  /usr/bin/make V=1 CXX="${CXX} ${CC_SYSROOT}" CC="${CC_TMP} ${CC_SYSROOT}" SHLIBDIR=/usr/X11R7/${B_LIBDIRS} \
       LOCAL_LDFLAGS="-L${SYSROOT}/usr/X11R7/${B_LIBDIRS}" ${MAKEOPTS} ${ARCHMOPT} DESTDIR=${DIST_ROOT} ${MAKEITARGETS} install || return 1
}

cmake_cross_build() {
#  export LD_LIBRARY_PATH="${RPATH_LINK}"
  export CC="${CC} --sysroot=${SYSROOT} -Wl,--rpath-link=${RPATH_LINK}"
  export CXX="${CXX} --sysroot=${SYSROOT}/ -Wl,--rpath-link=${RPATH_LINK}"
  export LDFLAGS="${LDFLAGS} ${EXTRALIBS}"

  if [ "${2}" == "${NARCH}" ];then
    cmake -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX} \
          -DCMAKE_C_FLAGS="${MLOPT} --sysroot=${SYSROOT}/ ${CFLAGS}" \
          -DCMAKE_CXX_FLAGS="${MLOPT} --sysroot=${SYSROOT}/ ${CPPLAGS}" \
          -DCMAKE_C_LINK_FLAGS="${MLOPT} --sysroot=${SYSROOT}/ ${LDFLAGS} ${EXTRALIBS}" \
          -DCMAKE_STANDARD_LIBRARIES="${EXTRALIBS}" \
          -DCMAKE_INSTALL_RPATH:PATH="${RPATH_LINK}" ${CONFOPT} ${ARCHXOPT} ${ARCHOPT} ${1}${CFGBIN}
   else
    cmake -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX} \
          -DCMAKE_SYSTEM_NAME=Linux  -DCMAKE_FIND_ROOT_PATH=${SYSROOT}/ \
          -DCMAKE_C_FLAGS="${MLOPT} --sysroot=${SYSROOT}/ ${CFLAGS}" \
          -DCMAKE_CXX_FLAGS="${MLOPT} --sysroot=${SYSROOT}/ ${CPPLAGS}" \
          -DCMAKE_C_LINK_FLAGS="${MLOPT} --sysroot=${SYSROOT}/ ${LDFLAGS} ${EXTRALIBS}" \
          -DCMAKE_STANDARD_LIBRARIES="${EXTRALIBS}" \
          -DCMAKE_INSTALL_RPATH:PATH="${RPATH_LINK}" ${CONFOPT} ${ARCHXOPT} ${ARCHOPT} \
          -DCMAKE_C_COMPILER="${MLHOST}-gcc" -DCMAKE_C_COMPILER_ENV_VAR="${CC_SYSROOT}" \
          -DCMAKE_CXX_COMPILER="${MLHOST}-g++" -DCMAKE_CXX_COMPILER_ENV_VAR="${CC_SYSROOT}" \
          -DGNU_HOST=${3} -DCMAKE_TOOLCHAIN_FILE=${SCRIPTDIR}/cmake_${2}.cross ${1}${CFGBIN}
  fi;
  cmake ${CONFOPT} ${ARCHXOPT} ${ARCHOPT} -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX} ${1}${CFGBIN}

  #Postconfig hook
  if [ -e ${SRCDIR}/${PSOURCEDIR}/.build-info/post-config ];then
    sh ${SRCDIR}/${PSOURCEDIR}/.build-info/post-config ${2} ${SRCDIR}/${PSOURCEDIR} ${DIST_ROOT}
  fi;

  /usr/bin/make ${MAKE_J} V=1 ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} && \
    /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEITARGETS} install
  RES=$?
  if [ ${RES} != 0 ] && [ "${MAKE_J}" ];then
    /usr/bin/make V=1 ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} || return 1
    /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEITARGETS} install || return 1
   elif [ ${RES} != 0 ];then
     return 1
  fi;
}

autoconf_cross_build() {
  if [ "${CLEARFLAGS}" ] && [ "${CLEARFLAGS}" == "1" ];then
    unset CFLAGS CPPFLAGS CXXFLAGS LDFLAGS LD
    export CC="/usr/bin/${CC} --sysroot=${SYSROOT}/ ${MLOPT}"
    export CXX="/usr/bin/${CXX} --sysroot=${SYSROOT}/ ${MLOPT}"
    if [ "${ADDLDFLAG}" ];then
      export LDFLAGS="${ADDLDFLAG}"
    fi;
    if [ "${ADDCFLAG}" ];then
      export CFLAGS=${ADDCFLAG}
#      export CPPFLAGS=${ADDCFLAG}
      export CXXFLAGS=${ADDCFLAG}
    fi;
   else
    export CC="/usr/bin/${CC} ${CC_SYSROOT}"
    export CXX="/usr/bin/${CXX} ${CC_SYSROOT}"
    export AS="${CC} ${CFLAGS}"
    export CC="${CC}"
    export CXX="${CXX}"
  fi;

  if [ "${LDISCC}" == "1" ];then
    export LD="${CC}"
   else
    export LD="${MLHOST}-ld --sysroot=${SYSROOT}/${MLLDOPT} --rpath-link=${RPATH_LINK}"
  fi;

#  export LD_LIBRARY_PATH="${RPATH_LINK}"
  if [ ! "${STDOPTS}" ];then
    STDOPTSX="--prefix=${PREFIX} --sysconfdir=/etc/${SYSCONFPRE} --mandir=${PREFIX}/share/man --localstatedir=/var --infodir=${PREFIX}/share/info" 
    if [ "${B_LIBDIRS}" ];then
      STDOPTSX="${STDOPTSX} --libdir=${PREFIX}/${B_LIBDIRS}";
      if [ "${LIBDIRPRE}" ];then
        STDOPTSX="${STDOPTSX}/${LIBDIRPRE}";
      fi;
    fi;
    if [ "${2}" != "${NARCH}" ] && [ ! "${MLOPT}" ];then
      STDOPTSX="${STDOPTSX} cross_compiling=yes --host=${3} --build=${BUILD}"
     elif [ "${NOCROSS}" == "1" ];then
      STDOPTSX="${STDOPTSX} --host=${3} --build=${3}"
     else
      STDOPTSX="${STDOPTSX} --host=${3} --build=${BUILD}"
    fi;
   else
    STDOPTSX=${STDOPTS}
  fi;

  #Disable shared libs for c++ libs where libstdc++ is not shared
  if [ "${STDCSTATIC}" ] && [ ! -f /usr/${B_LIBDIRS}/libstdc++.so ];then
    STDOPTSX="${STDOPTSX} ${STDCSTATIC}";
  fi;

  if [ "${ADDBUILDSYSROOT}" == "1" ] && [ -d ${ARCHROOT}/${2} ] && [ ! -h ${ARCHROOT}/${1} ];then
    STDOPTSX="${STDOPTSX} --with-build-sysroot=${ARCHROOT}/${2}";
   elif [ "${ADDBUILDSYSROOT}" == "1" ] && [ "${2}" == "${NARCH}" ];then
    STDOPTSX="${STDOPTSX} --with-build-sysroot=/";
  fi;

  if [ "${ADDWITHSYSROOT}" == "1" ] && [ -d ${ARCHROOT}/${2} ] && [ ! -h ${ARCHROOT}/${1} ];then
    STDOPTSX="${STDOPTSX} --with-sysroot=${ARCHROOT}/${2}"
   elif [ "${ADDWITHSYSROOT}" == "1" ] && [ "${2}" == "${NARCH}" ];then
    STDOPTSX="${STDOPTSX} --with-sysroot=/"
  fi;

  if [ "${GOBJECTINTRO}" ] && [ "${GOBJECTINTRO}" == "1" ] && [ "${2}" != "${NARCH}" ];then
    if [ ! -d ${ARCHROOT}/${2}/usr/${B_LIBDIRS}/gobject-introspection ];then
      STDOPTSX="${STDOPTSX} --enable-introspection=no"
     else
      STDOPTSX="${STDOPTSX} --enable-introspection=yes"
    fi;
  fi;

  #Preconfig hook
  if [ -e ${SRCDIR}/${PSOURCEDIR}/.build-info/pre-config ];then
    sh ${SRCDIR}/${PSOURCEDIR}/.build-info/pre-config ${2} ${SRCDIR}/${PSOURCEDIR} ${DIST_ROOT}
  fi;

  if [ "${NOCCOPT}" ] && [ "${NOCCOPT}" == "1" ] && [ "${EXTRALIBS}" ];then
    ${1}${CFGBIN}configure ${STDOPTSX} ${CONFOPT} ${ARCHOPT} ${ARCHXOPT} LIBS="${EXTRALIBS}" || return 1
   elif [ "${NOCCOPT}" ] && [ "${NOCCOPT}" == "1" ];then
    ${1}${CFGBIN}configure ${STDOPTSX} ${CONFOPT} ${ARCHOPT} ${ARCHXOPT} || return 1
   elif [ "${EXTRALIBS}" ];then
    ${1}${CFGBIN}configure ${STDOPTSX} ${CONFOPT} ${ARCHOPT} ${ARCHXOPT} CC="${CC}" CXX="${CXX}" LIBS="${EXTRALIBS}" || return 1
   else
    ${1}${CFGBIN}configure ${STDOPTSX} ${CONFOPT} ${ARCHOPT} ${ARCHXOPT} CC="${CC}" CXX="${CXX}" || return 1
  fi;

  #Postconfig hook
  if [ -e ${SRCDIR}/${PSOURCEDIR}/.build-info/post-config ];then
    sh ${SRCDIR}/${PSOURCEDIR}/.build-info/post-config ${2} ${SRCDIR}/${PSOURCEDIR} ${DIST_ROOT}
  fi;

  sysroot_fixup ${2}

  #config make hook
  if [ -e ${SRCDIR}/${PSOURCEDIR}/.build-info/make-config ];then
    sh ${SRCDIR}/${PSOURCEDIR}/.build-info/make-config ${NARCH} ${SRCDIR}/${PSOURCEDIR} ${DIST_ROOT} ${HOST}
   else
    if [ "${ADDCC}" ] && [ "${ADDCC}" == "0" ];then
      /usr/bin/make ${MAKE_J} HOSTCC="${BUILD}-gcc" HOSTLD="${BUILD}-gcc" HOSTCC_LDFLAGS="-L/lib64 -L/libx32 -L/lib -L/usr/lib64 -L/usr/libx32 -L/usr/lib" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} && \
        /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} install
      RES=$?
      if [ ${RES} != 0 ] && [ "${MAKE_J}" ];then
        /usr/bin/make HOSTCC="${BUILD}-gcc" HOSTLD="${BUILD}-gcc" HOSTCC_LDFLAGS="-L/lib64 -L/libx32 -L/lib -L/usr/lib64 -L/usr/libx32 -L/usr/lib" ${MAKEOPTS} ${ARCHMOPT} ${MAKEALL} ${MAKETARGETS} &&\
        /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEITARGETS} install || return 1
       elif [ ${RES} != 0 ];then
        return 1
      fi;
     else
      /usr/bin/make ${MAKE_J} LD="${LD}" CC="${CC}" CXX="${CXX}" HOSTCC="${BUILD}-gcc" \
        HOSTCC_LDFLAGS="-L/lib64 -L/libx32 -L/lib -L/usr/lib64 -L/usr/libx32 -L/usr/lib" ${MAKEOPTS} ${ARCHMOPT} \
        ${MAKEALL} ${MAKETARGETS} && \
      /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEITARGETS} install
      RES=$?
      if [ ${RES} != 0 ] && [ "${MAKE_J}" ];then
        /usr/bin/make LD="${LD}" CC="${CC}" CXX="${CXX}" HOSTCC="${BUILD}-gcc" \
          HOSTCC_LDFLAGS="-L/lib64 -L/libx32 -L/lib -L/usr/lib64 -L/usr/libx32 -L/usr/lib" ${MAKEOPTS} ${ARCHMOPT} \
          ${MAKEALL} ${MAKETARGETS} || return 1
        /usr/bin/make DESTDIR=${DIST_ROOT} ${MAKEOPTS} ${ARCHMOPT} ${MAKEITARGETS} install || return 1
       elif [ ${RES} != 0 ];then
        return 1
      fi;
    fi
  fi;
}

build_project() {
  BUILDPROJECT=${1}
  shift;
  barch=${1};

  eval `cat ${DEFDIR}/${BUILDPROJECT}`

  if [ ! "${ALIAS}" ];then
    export PROJECT=${BUILDPROJECT}
   else
    export PROJECT=${ALIAS};
  fi;

  if [ ! "${MAKEALL}" ];then
    MAKEALL=all
  fi;

  if [ ! "${PREFIX}" ];then
    echo "PREFIX not defined";
    return 1;
  fi;

  AVER=VERSION_${1}
  VERSION=${!AVER-$VERSION}

  #For null config i need this set up early
  if [ "${AMVER}" ];then
    ACLOCAL=aclocal-${AMVER}
    AUTOMAKE=automake-${AMVER}
   else
    ACLOCAL=aclocal-${AMDEF}
    AUTOMAKE=automake-${AMDEF}
  fi;
  export ACLOCAL AUTOMAKE

  svn_load_pkg ${PROJECT} ${PROJECT}${VERSEP}${VERSION}

  if [ "${VERSION}" ];then
    if [ -d ${SRCDIR}/${PROJECT}/${PROJECT}${VERSEP}${VERSION} ];then
      export PKG=${BUILDPROJECT}${VERSEP}${VERSION}
      export PSOURCEDIR=${PROJECT}/${PROJECT}${VERSEP}${VERSION}
     elif [ -d ${SRCDIR}/${PROJECT}${VERSEP}${VERSION} ];then
      export PKG=${BUILDPROJECT}${VERSEP}${VERSION}
      export PSOURCEDIR=${PROJECT}${VERSEP}${VERSION}
     else
      echo "Project Dir Not Found ${SRCDIR}/${PROJECT}${VERSEP}${VERSION}";
      return 1
    fi;
   else
    export PKG=${BUILDPROJECT}
    export PSOURCEDIR=${PROJECT}${VERSEP}${VERSION}
  fi;
  export VERSION

  if [ "${PSOURCEDIR}" ] && [ ! -d ${SRCDIR}/${PSOURCEDIR} ];then
    echo "No Such Project"
    return 1
  fi;

  if [ ! "${BUILDDIR}" ];then
    export BUILDDIR=1;
  fi;

  if [ ! "${SYSROOTFIXUP}" ];then
    SYSROOTFIXUP="1";
  fi;
  export SYSROOTFIXUP;

  if [ ! "${LDIGNORE}" ];then
    LDIGNORE="0";
  fi;
  export LDIGNORE;

  if [ ! "${FIXUPLIB}" ];then
    FIXUPLIB="0";
  fi;
  export FIXUPLIB;

  if [ "${ADDPATH}" ];then
    PATH="${PATH}:${ADDPATH}"
  fi;
  export PATH="${PATH}:/opt/qt-4/bin:${ADDPATH}"
  echo Building ${PKG}

  if [ ! "${CFGPTH}" ];then
    cd ${SRCDIR}/${PSOURCEDIR}
    TOPDIR=./
   else
    cd ${SRCDIR}/${PSOURCEDIR}/${CFGPTH}
    TOPDIR=../
  fi;

  if [ ${BUILDDIR} == "1" ];then
    TOPDIR=${TOPDIR}../
  fi;

  if [ "${JAVA_HOME}" ];then
    export JAVA_HOME
    export PATH=${JAVA_HOME}/bin:${PATH}
  fi;

  if [ "${ANT_HOME}" ];then
    export ANT_HOME
    export PATH=${ANT_HOME}/bin:${PATH}
  fi;

  SYSPATH=${PATH}

  if [ -x /usr/bin/which ] || [ -x /bin/which ];then
    export RSYNC=$( which rsync );
   elif [ -x /usr/bin/rsync ];then
     export RSYNC=/usr/bin/rsync;
   else
     export RSYNC=true
  fi;

  if [ "${CANBUILD}" ] && [[ ${barch} != *${CANBUILD}* ]];then
    return 0;
  fi;

  if [ -d ${ARCHROOT}/${barch} ] && [ ! -h ${ARCHROOT}/${barch} ];then
    export SYSROOT=${ARCHROOT}/${barch};
   elif [ "${barch}" == "${NARCH}" ];then
    export SYSROOT="";
  fi;

  if [ ! -d ${SYSROOT} ];then
    return 0;
  fi;

  MOPTIN=MOPT_${barch}
  AOPTIN=OPT_${barch}

  #use eval ${MOPTIN}=XXXX to set it
  ARCHMOPT=${!MOPTIN}
  ARCHOPT=${!AOPTIN}

  if [ "${barch}" != "${NARCH}" ];then
    XOPTIN=OPTX_${barch}
    ARCHXOPT="${CONFOPTX} ${!XOPTIN}"
   else
    ARCHXOPT="";
  fi;

  if [ "${NARCH}" == "x86_64" ];then
    if [ "${barch}" == "i686" ] || [ "${barch}" == "x86_32" ];then
      export LD_LIBRARY_PATH="${SYSROOT}/${B_LIBDIRS}:${SYSROOT}/usr/${B_LIBDIRS}:${SYSROOT}/usr/X11R7/${B_LIBDIRS}:${SYSROOT}/usr/lib/perl/x86_64-linux/CORE";
      if [ "${SYSROOTPATH}" == "1" ];then
        export PYTHON=${SYSROOT}/usr/bin/python
        export PYTHONHOME=${SYSROOT}/usr
        export PYTHONPATH=${SYSROOT}/usr/${B_LIBDIRS}/gobject-introspection/giscanner:${SYSROOT}/usr/${B_LIBDIRS}/gobject-introspection
        export PATH="${SYSROOT}/sbin:${SYSROOT}/bin:${SYSROOT}/usr/sbin:${SYSROOT}/usr/bin:${SYSROOT}/usr/X11R7/bin:${SYSPATH}";
        eval `chroot ${SYSROOT} /usr/bin/perl -V:privlib -V:archlib -V:sitearch -V:sitelib`
        export PERL5LIB=${SYSROOT}/${privlib}:${SYSROOT}/${archlib}:${SYSROOT}/${sitearch}:${SYSROOT}/${sitelib}
      fi;
#      export PERL5LIB="${SYSROOT}/usr/lib/perl5/5.16.2/x86_64-linux-thread-multi";
#      eval `perl -V:archlib -V:sitelib -V:sitearch -V:privlib`
#      export PERL5LIB="${SYSROOT}/${sitearch}:${SYSROOT}/${sitelib}:${SYSROOT}/${archlib}:${SYSROOT}/${privlib}"
     else
      if [ "${SYSROOTPATH}" == "1" ];then
        export PYTHON=${SYSROOT}/usr/bin/python
        export PYTHONHOME=${SYSROOT}/usr
        export PATH="${SYSROOT}/sbin:${SYSROOT}/bin:${SYSROOT}/usr/sbin:${SYSROOT}/usr/bin:${SYSROOT}/usr/X11R7/bin:${SYSPATH}";
       else
        export PATH=${SYSPATH}
      fi;
      unset LD_LIBRARY_PATH PYTHONHOME PERL5LIB
    fi;
   else
    unset LD_LIBRARY_PATH PYTHONHOME PERL5LIB
    export PATH=${SYSPATH}
  fi;

  if [ -d ${ARCHROOT}/${barch}/opt/qt-4 ] && [ ! -h ${ARCHROOT}/${barch} ];then
    export QTDIR=${ARCHROOT}/${barch}/opt/qt-4
   elif [ -d /opt/qt-4 ];then
    export QTDIR=/opt/qt-4
  fi;

  CFLAGS="${ADDCFLAG} -I=/include -I=/usr/include -I=/usr/X11R7/include -I=/usr/include/glib-2.0 -I=/usr/include/gtk-2.0 -I=/usr/include/dbus-1.0 -I=/opt/qt-4/include";
  if [ "${JAVA_HOME}" ] && [ -d ${JAVA_HOME}/include ];then
    CFLAGS="${CFLAGS} -I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux";
  fi
  LDFLAGS="-L=/usr/${B_LIBDIRS} -L=/${B_LIBDIRS} -L=/opt/qt-4/${B_LIBDIRS} -L=/usr/X11R7/${B_LIBDIRS} ${ADDLDFLAG}"
  if [ "${SETCPPTOC}" == "1" ];then
    CPPFLAGS=${CFLAGS};
  fi;
  CPPFLAGS="${ADDCPPFLAG}";
  if [ "${CPPFLAGS}" ];then
    export CPPFLAGS
  fi;
  export FORCE_UNSAFE_CONFIGURE=1
#    export PKG_CONFIG_SYSROOT_DIR="${SYSROOT}"
  export PKG_CONFIG_PATH="${SYSROOT}/${B_LIBDIRS}/pkgconfig:${SYSROOT}/usr/${B_LIBDIRS}/pkgconfig:${SYSROOT}/opt/apache2/${B_LIBDIRS}/pkgconfig:${SYSROOT}/usr/share/${B_LIBDIRS}/pkgconfig:${SYSROOT}/usr/X11R7/${B_LIBDIRS}/pkgconfig:${SYSROOT}/lib/pkgconfig:${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/opt/qt-4/${B_LIBDIRS}/pkgconfig/";
#  export PYTHONPATH="/usr/${B_LIBDIRS}/python2.7/site-packages/"

  if [ ! "${MLOPT}" ] && [ "${NARCH}" != "${barch}" ];then
    if [ "${LDIGNORE}" != "0" ];then
      XCCOPT=" -Wl,--unresolved-symbols=ignore-in-shared-libs";
      XCCOPTLD=" -Wl,--unresolved-symbols=ignore-all";
    fi;
#    LDFLAGS="${LDFLAGS} ${XCCOPTLD}"
  fi;

  RPATH_LINK="${SYSROOT}/usr/${B_LIBDIRS}:${SYSROOT}/${B_LIBDIRS}:${SYSROOT}/usr/X11R7/${B_LIBDIRS}:${SYSROOT}/usr/${B_LIBDIRS}/pulseaudio:${SYSROOT}/opt/qt4/${B_LIBDIRS}"
  RPLINK=" -Wl,--rpath-link=${RPATH_LINK}";
  XCCOPT="${XCCOPT} ${RPLINK}"

  export MLOPT MLHOST MLLDOPT

  export CC_SYSROOT="--sysroot=${SYSROOT}/ ${MLOPT} ${XCCOPT} -L=/usr/${B_LIBDIRS} -L=/${B_LIBDIRS} -L=/usr/X11R7/${B_LIBDIRS} -I=/include -I=/usr/include -I=/usr/X11R7/include";
  export CC="${MLHOST}-gcc";
  export CXX="${MLHOST}-g++"
  LD="${MLHOST}-ld${MLLDOPT}"

  #XXX /build AKA ARCHROOT
  if [ ! "${ADDGCCDIR}" ] || [ "${ADDGCCDIR}" == "1" ];then
    GCCDIR=$( ${CC} ${CC_SYSROOT} -print-libgcc-file-name |sed -e "s/libgcc\.a$//" -e "s/x32\/$//" -e "s/32\/$//" )
    if [ "${GCCDIR}" ] && [ -d ${GCCDIR}/include ] && [ -d ${ARCHROOT}/${barch} ] && [ ! -d ${ARCHROOT}/${barch}/${GCCDIR}/include ];then
      rsync -avPR ${GCCDIR}/ ${ARCHROOT}/${barch}/
      CFLAGS="${CFLAGS} -I${GCCDIR}/include";
     elif [ -d ${GCCDIR}/include ];then
      CFLAGS="${CFLAGS} -I${GCCDIR}/include";
     elif [ -d ${GCCDIR}/../include ];then
      CFLAGS="${CFLAGS} -I${GCCDIR}/../include";
    fi;
  fi;

  if [ ! "${LDISCC}" ] || [ "${LDISCC}" == "1" ];then
    LDFLAGS="${LDFLAGS} ${RPLINK}";
  fi;

  export AR="${MLHOST}-ar"
  export AS="${MLHOST}-as"
  export NM="${MLHOST}-nm"
  export RANLIB="${MLHOST}-ranlib"
  export OBJCOPY="${MLHOST}-objcopy"
  export STRIP="${MLHOST}-strip"

  if [ ${BUILDDIR} == "1" ];then
    if [ ! -d build-${barch} ];then
      mkdir build-${barch}
     elif [ "${CLEANOPT}" == "clean" ] || [ "${CLEANOPT}" == "distclean" ];then
      rm -rf build-${barch} > /dev/null 2>&1
      mkdir build-${barch}
    fi;
    cd build-${barch}
   elif [ "${NOCLEAN}" != "1" ];then
    if [ "${CLEANOPT}" == "clean" ];then
      /usr/bin/make ${CLEANOPT} > /dev/null 2>&1
     else
      (/usr/bin/make distclean || /usr/bin/make clean) > /dev/null 2>&1
    fi;
  fi;

  if [ "${AUTORECONF}" ] && [ "${AUTORECONF}" == "1" ];then
    (cd ${TOPDIR};autoreconf)
  fi;

  export DIST_ROOT=${PKGBUILDDIR}/${barch}/${PKG}
  if [ -d ${DIST_ROOT} ];then
    rm -rf ${DIST_ROOT}
  fi;
  mkdir -p ${DIST_ROOT}

  export LDFLAGS="${LDFLAGS} -L${DIST_ROOT}/${B_LIBDIRS} -L${DIST_ROOT}/usr/${B_LIBDIRS}";
  export CPPFLAGS="${CFLAGS}"
  export CXXFLAGS="${CFLAGS}"
  export CFLAGS

  if [ -x ${SCRIPTDIR}/make_${PROJECT} ];then
    export CC="${CC} ${CC_SYSROOT}"
    export CXX="${CXX} ${CC_SYSROOT}"
    ${SCRIPTDIR}/make_${PROJECT} ${barch} ${HOST} ${DIST_ROOT} ${CLEANOPT} || return 1
   elif [ -e ${TOPDIR}${CFGBIN}configure ];then
    if [ ! -x ${TOPDIR}${CFGBIN}configure ];then
      chmod 755 ${TOPDIR}${CFGBIN}configure
    fi;
    autoconf_cross_build ${TOPDIR} ${barch} ${HOST} || return 1;
   elif [ -e ${TOPDIR}${CFGBIN}./cmake ] || [ -e ${TOPDIR}${CFGBIN}/CMakeLists.txt ];then
    cmake_cross_build ${TOPDIR} ${barch} ${HOST} || return 1;
   elif [ -e ${TOPDIR}${CFGBIN}./Imakefile ];then
    imake_cross_build ${barch} || return 1;
   elif [ -e ${TOPDIR}${CFGBIN}./setup.py ];then
    python setup.py clean --all
    python ${TOPDIR}${CFGBIN}./setup.py install --root=${DIST_ROOT} || return 1
   elif [ ! -e ${TOPDIR}${CFGBIN}configure ] &&
        [ ! -e configure ] &&
        [ ! -e ${TOPDIR}configure ] &&
        [ ! -e cmake ] &&
        [ ! -e ${TOPDIR}${CFGBIN}cmake ] &&
        [ ! -e ${TOPDIR}cmake ];then
    make_cc_destdir || return 1
   else
    echo "no build method"
    return 1
  fi;

  if [ ! -d ${STATDIR}/${barch}/done ];then
    mkdir -p ${STATDIR}/${barch}/done
  fi;

  if [ -e ${STATDIR}/${barch}/fail/${BUILDPROJECT} ];then
    rm ${STATDIR}/${barch}/fail/${BUILDPROJECT}
  fi;
  touch ${STATDIR}/${barch}/change
  touch ${STATDIR}/${barch}/done/${BUILDPROJECT}
  echo ${BUILDPROJECT} >> ${STATDIR}/${barch}/built

  #Move 64bit libs into lib64
  if [ "${FIXUPLIB}" == "1" ];then
    if [ "${B_LIBDIRS}" == "lib64" ];then
      for libdir in / /usr /usr/local ${PREFIX};do
        if [ -d ${DIST_ROOT}${libdir}/lib ];then
          if [ ! -d ${DIST_ROOT}${libdir}/lib64 ];then
            mkdir -p ${DIST_ROOT}${libdir}/lib64
          fi;
          mv ${DIST_ROOT}${libdir}/lib/* ${DIST_ROOT}${libdir}/lib64/
          rm -rf ${DIST_ROOT}${libdir}/lib
        fi; # sed -i -e "s/\(\-L=\)\/lib\//\/libx32\//g" ${DIST_ROOT}${libdir}/lib64/*.la
        libtool finish ${DIST_ROOT}${libdir}/lib64
      done;
     elif [ "${barch}" == "x86_32" ];then
      for libdir in / /usr /usr/local ${PREFIX};do
        if [ -d ${DIST_ROOT}${libdir}/lib ];then
          if [ ! -d ${DIST_ROOT}${libdir}/libx32 ];then
            mkdir -p ${DIST_ROOT}${libdir}/libx32
          fi;
          mv ${DIST_ROOT}${libdir}/lib/* ${DIST_ROOT}${libdir}/libx32/
          rm -rf ${DIST_ROOT}${libdir}/lib
        fi;
        if [ -d ${DIST_ROOT}${libdir}/lib64 ];then
          if [ ! -d ${DIST_ROOT}${libdir}/libx32 ];then
            mkdir -p ${DIST_ROOT}${libdir}/libx32
          fi;
          mv ${DIST_ROOT}${libdir}/lib64/* ${DIST_ROOT}${libdir}/libx32/
          rm -rf ${DIST_ROOT}${libdir}/lib64
        fi; 
        if [ -d ${DIST_ROOT}${libdir}/libx3264 ];then
          if [ ! -d ${DIST_ROOT}${libdir}/libx32 ];then
            mkdir -p ${DIST_ROOT}${libdir}/libx32
          fi;
          mv ${DIST_ROOT}${libdir}/libx3264/* ${DIST_ROOT}${libdir}/libx32/
          rm -rf ${DIST_ROOT}${libdir}/libx3264
        fi; # sed -i -e "s/\(\-L=\)\/lib\//\/libx32\//g" ${DIST_ROOT}${libdir}/libx32/*.la
        libtool finish ${DIST_ROOT}${libdir}/libx32
      done;
    fi;
  fi;

  if [ ${B_LIBDIRS} != "lib" ] && [ -d ${DIST_ROOT}/usr/${B_LIBDIRS}/python2.7 ];then
    if [ ! -d ${DIST_ROOT}/usr/lib/python2.7/ ];then
      mkdir -p ${DIST_ROOT}/usr/lib/python2.7/
    fi;
    rsync -avP ${DIST_ROOT}/usr/${B_LIBDIRS}/python2.7/ ${DIST_ROOT}/usr/lib/python2.7/
    rm -rf ${DIST_ROOT}/usr/${B_LIBDIRS}/python2.7/
    ln -s /usr/lib/python2.7 ${DIST_ROOT}/usr/${B_LIBDIRS}/python2.7
  fi;

  #Postinstall hook
  if [ -e ${SRCDIR}/${PSOURCEDIR}/.build-info/post-install ];then
    sh ${SRCDIR}/${PSOURCEDIR}/.build-info/post-install ${barch} ${SRCDIR}/${PSOURCEDIR} ${DIST_ROOT}
  fi;

  #Build Distributibils
  tar_package ${DIST_ROOT} ${PKGDISTDIR}/${barch} ${PKG} > /dev/null 2>&1

  if [ "${barch}" == "${NARCH}" ];then
    if [ -d ${DIST_ROOT} ];then
      ${RSYNC} -avP ${DIST_ROOT}/ /
    fi;
#   elif [ "${barch}" == "x86_32" ] && [ "${NARCH}" == "x86_64" ];then
#    if [ -d ${DIST_ROOT}/${B_LIBDIRS} ];then
#      ${RSYNC} -avP ${DIST_ROOT}/${B_LIBDIRS} /
#    fi;
#    if [ -d ${DIST_ROOT}/usr/${B_LIBDIRS} ];then
#      ${RSYNC} -avP ${DIST_ROOT}/usr/${B_LIBDIRS} /usr/
#    fi;
  fi;

  if [ -d ${ARCHROOT}/${barch} ] && [ ! -h ${ARCHROOT}/${barch} ];then
    ${RSYNC} -avP ${DIST_ROOT}/ ${ARCHROOT}/${barch}/
  fi;
}

setup_build_dir() {
  cd ${SRCDIR}/${2}/${3}
  if [ -d build-${4}-${1}${5} ];then
    rm -rf build-${4}-${1}${5}
  fi;
  if [ -d ${TOOLDIR}/${4}/${1}/${3}${5} ];then
    rm -rf ${TOOLDIR}/${4}/${1}/${3}${5}
  fi;
  if [ ! -d build-${4}-${1}${5} ];then
    mkdir build-${4}-${1}${5}
  fi;
  cd build-${4}-${1}${5}
}

build_glibc() {
  if [ -e ${STATDIR}/${1}/done/glibc ];then
    return;
  fi;

  CLEANOPT=distclean
  case $1 in
    i[3-6]86|x86_32)MLHOST=x86_64-linux-gnu;;
    *)MLHOST=${2};;
  esac;

  case $1 in
    i[3-6]86)MLOPT=-m32;;
    x86_32)MLOPT=-mx32;;
    *)MLOPT="";;
  esac;

  if [ -x /usr/bin/${MLHOST}-gcc ];then
    GCCEH=`${MLHOST}-gcc ${MLOPT} -print-libgcc-file-name |sed 's/libgcc/&_eh/'`
    if [ ! -e ${GCCEH} ];then
      ln -s libgcc.a ${GCCEH}
    fi;
  fi;

  if [ "${1}" != "${NARCH}" ] && [ ! -d /build/${1} ];then
    mkdir -p ${ARCHROOT}/${1}
   elif [ "${1}" == "${NARCH}" ];then
    if [ ! -d ${ARCHROOT} ];then
      mkdir -p ${ARCHROOT}
    fi;
    ln -s / ${ARCHROOT}/${NARCH}
  fi;

  if [ ! -e /bin/pwd ] && [ -e /usr/bin/pwd ];then
    ln -s /usr/bin/pwd /bin/
  fi;

  check_create_arch ${1}
  build_project glibc ${1}
  RES=$?
  if [ -h ${GCCEH} ];then
    rm ${GCCEH}
  fi;
  if [ ${RES} != 0 ];then
    return 1;
  fi;
  #Create a static libc pkg
  if [ "${1}" == "${NARCH}" ];then
    USELIBDIR=${NLIBDIR}
   else
    USELIBDIR=${B_LIBDIRS}
  fi;
  SRDIR=${BASEROOT}/${1}
  if [ ! -d ${SRDIR} ];then
    mkdir -p ${SRDIR}/usr/include
  fi;
  if [ ! -d ${TOOLPKG}/${1}/${PKG} ];then
    mkdir -p ${TOOLPKG}/${1}/${PKG}
  fi;
  cd ${DIST_ROOT}
  rsync -a . ${SRDIR}/
  MULTIARCH=MARCH_${NARCH}

  if [ "${1}" != "${NARCH}" ] && [[ ${1} =~ ${!MULTIARCH} ]];then
    rsync -aR ${USELIBDIR} usr/${USELIBDIR} /;
    rsync -aR ${USELIBDIR} usr/${USELIBDIR} ${BASEROOT}/${NARCH}/;

    #Makesure the MA stubs are available
    rsync -avPR /usr/include/gnu/stubs* ${BASEROOT}/${1}/
    rsync -avPR /usr/include/gnu/stubs* ${ARCHROOT}/${1}/
  fi;

  #Arch include dir
  if [ ! -d  /usr/${2}/include ];then
    mkdir -p /usr/${2}/include
  fi;
  rsync -a usr/include /usr/${2}/include

  tar -cJf ${TOOLPKG}/${1}/${PKG}/${PKG}-static.tar.xz usr/${USELIBDIR}/*.o usr/${USELIBDIR}/*.a usr/include
}

#Single configure template for bootstrap system
run_configure() {
  CONFLIBDIR=${1}
  shift;
  ../configure --libdir=/usr/${CONFLIBDIR} --prefix=${PREFIX} --sysconfdir=/etc --mandir=/usr/share/man \
               --infodir=/usr/share/info --localstatedir=/var $@ || return 1
}

build_bootstrap_binutils() {
  eval `cat ${DEFDIR}/binutils`;
  AVER=VERSION_${1}
  VERSION=${!AVER-$VERSION}
  BINUTILS=binutils${VERSEP}${VERSION}

  if [ "${1}" == "${NARCH}" ];then
    DIST_ROOT=${TOOLDIR}/${NARCH}/${BINUTILS}-static
   else
    DIST_ROOT=${TOOLDIR}/${NARCH}/${1}/${BINUTILS}
  fi;

  if [ ! -e /usr/bin/${2}-ld ] || [ ! -d ${DIST_ROOT} ];then
    svn_load_pkg binutils ${BINUTILS} || return 1
    ARCHOPTV=OPT_${1}
    ARCHOPT=${!ARCHOPTV}

    if [ "${1}" == "${NARCH}" ];then
      PROGPRE="";
      ARCHOPT="${ARCHOPT} LDFLAGS=-static";
      MAKEOPT="LDFLAGS=-all-static";
     else
      MAKEOPT="";
      PROGPRE="--program-prefix=${2}-";
    fi;

    setup_build_dir ${1} binutils ${BINUTILS} ${NARCH}
    export MAKEOPT
    run_configure ${B_LIBDIRS} ${PROGPRE} --target=${2} --build=${BUILD} --host=${BUILD} \
                  ${CONFOPT} ${ARCHOPT} || return 1
    make configure-host || return 1
    make ${MAKE_J} ${MAKEOPT} all || make ${MAKEOPT} all || return 1
    make DESTDIR=${DIST_ROOT} all install || return 1

    if [ "${1}" != "${NARCH}" ];then
      if [ ! -e /usr/bin/${2}-ld ];then
        rsync -aP ${DIST_ROOT}/ /
      fi;
      MULTIARCH=MARCH_${NARCH}
      if [[ ${1} =~ ${!MULTIARCH} ]];then
        rsync -a ${DIST_ROOT}/usr/${2} ${BASEROOT}/${NARCH}/usr/;
      fi;
      tar_package ${DIST_ROOT} ${TOOLPKG}/${NARCH}/${1} ${BINUTILS} > /dev/null 2>&1
     else
      tar_package ${DIST_ROOT} ${TOOLPKG}/${NARCH} ${BINUTILS}-static > /dev/null 2>&1
    fi;
  fi;
}

build_gcc_bootstrap() {
  eval `cat ${DEFDIR}/glibc`;
  AVER=VERSION_${1}
  VERSION=${!AVER-$VERSION}
  GLIBC=glibc${VERSEP}${VERSION}

  if [ "${3}" ] && [ "${3}" != "${NARCH}" ];then
    TARCH=${3}
    arch_config ${3}
    TLIBDIR=${SETLIBDIR}
    THOST=${TUPPLE}
   else
    TARCH=${NARCH}
    THOST=${BUILD}
    TLIBDIR=${NLIBDIR}
  fi;


  eval `cat ${DEFDIR}/gcc`;
  AVER=VERSION_${1}
  VERSION=${!AVER-$VERSION}
  GCC=gcc${VERSEP}${VERSION}

  if [ "${1}" != "${3}" ];then
    SYSROOT="--with-sysroot=/build/${1} ${CONFOPTX}";
    BUILDROOT=${ARCHROOT}/${1}
   else
    SYSROOT="--with-sysroot=/";
    if [ -d ${ARCHROOT}/${1} ];then
      BUILDROOT=${ARCHROOT}/${1}
     else
      BUILDROOT=""
    fi
  fi;
  if [ ! "${4}" ] || [ "${4}" == "static" ];then
    MARCH=BOOTOPT_${1}
    CONFOPT="${BOOTOPT} ${SYSROOT}"
    CFLAGS=-fPIC
    CXXFLAGS=-fPIC
    LDFLAGS="-static"
    SDIROPT=-boot
    MAKEOPT="LDFLAGS=-static";
   elif [ ! "${4}" ] || [ "${4}" == "null" ];then
    MARCH=BOOTOPT_${1}
    CONFOPT="${NULLOPT} ${SYSROOT}"
    CFLAGS=-fPIC
    CXXFLAGS=-fPIC
    SDIROPT=-null
   elif [ "${4}" == "cross" ];then
    if [ "${1}" == "${TARCH}" ];then
      return;
    fi;
    MARCH=CROSSOPT_${1}
    GCCLANG=LANG_${1}
    LANGOPT=${!GCCLANG}
    CFLAGS=-I=/usr/include
    CXXFLAGS=-I=/usr/include
    export CFLAGS CXXFLAGS
    CONFOPT="${CONFOPT} --with-jvm-root-dir=/usr/${TLIBDIR}/jvm/gcj-jdk-${1} --enable-cxx-flags=-I=/usr/include
             CFLAGS=-I=/usr/include ${LANGOPT} ${SYSROOT}"
    SDIROPT=-cross
    MAKEOPT="";
   elif [ "${4}" == "shared" ];then
    MARCH=CROSSOPT_${1}
    CFLAGS=-I=/usr/include
    CXXFLAGS=-I=/usr/include
    CONFOPT="${SHAREDOPT} ${CONFOPTX}"
    SDIROPT=-shared
    MAKEOPT="";
   elif [ "${4}" == "multi" ];then
    MARCH=CROSSOPT_${1}
    CFLAGS=-I=/usr/include
    CXXFLAGS=-I=/usr/include
    CONFOPT="${MULTIOPT} ${CONFOPTX}"
    SDIROPT=-multi
    MAKEOPT="";
  fi;
  TARGPKG=${GCC}${SDIROPT}

  if [ "${TARCH}" == "${1}" ];then
    GCCBOOTDEST=${TOOLDIR}/${TARCH}/${TARGPKG}
    PROGPRE="";
    USELIBDIR=${TLIBDIR}
   else
    GCCBOOTDEST=${TOOLDIR}/${TARCH}/${1}/${TARGPKG}
    PROGPRE="--program-prefix=${2}-";
    USELIBDIR=${B_LIBDIRS}
  fi;

  if [ -d ${GCCBOOTDEST} ];then
    return;
  fi;

  if which ${2}-gcc 2>/dev/null;then
    GCCLDIR=$( dirname `${2}-gcc --print-libgcc-file-name` )
    if [ -d ${GCCLDIR} ];then
      for booto in crti.o crt1.o crtn.o;do
        if [ -f /usr/${USELIBDIR}/${booto} ];then
          cp ${BUILDROOT}/usr/${USELIBDIR}/${booto} ${GCCLDIR}/
        fi;
      done;
#      CONFOPT="${CONFOPT} --with-stage1-ldflags=-L${GCCLDIR} --with-boot-ldflags=-L${GCCLDIR} CFLAGS=-B${GCCLDIR}";
    fi;
  fi;
  svn_load_pkg gcc ${GCC}
  setup_build_dir ${1} gcc ${GCC} ${TARCH} ${SDIROPT}

  #Use GLIBC/Kern headers only [Virgin] / Build dir / sysroot
  SRDIR=${BASEROOT}/${1}
  if [ -d ${PKGBUILDDIR}/${1}/${GLIBC}/usr/include ] && [ -d ${SRDIR}/usr/include/linux ] &&
     [ ${4} == "static" ];then
    BUILDDIR=${SRDIR}
    (cd ${PKGBUILDDIR}/${1}/${GLIBC}
    rsync -avP ${PKGBUILDDIR}/${1}/${GCC}/ ${SRDIR}/
    rsync -avPR . usr/include ${SRDIR}/
    if [ ! -d ${TOOLPKG}/${1}/${GLIBC} ];then
      mkdir -p ${TOOLPKG}/${1}/${GLIBC}
    fi;
    tar -cJf ${TOOLPKG}/${1}/${GLIBC}/${GLIBC}-headers.tar.xz usr/include)
   elif [ -d ${ARCHROOT}/${1}/ ] && [ ! -h ${ARCHROOT}/${1} ];then
    BUILDDIR=${ARCHROOT}/${1}/
   else
    BUILDDIR=/
  fi;

  export CFLAGS CXXFLAGS LDFLAGS
  run_configure ${USELIBDIR} ${PROGPRE} --build=${BUILD} --host=${THOST} --target=${2} --with-build-sysroot=${BUILDDIR} \
                ${CONFOPT} ${!MARCH} || return 1

  if [ ! -d ${2}/libstdc++-v3 ];then
    mkdir -p ${2}/libstdc++-v3
  fi;
  cp /usr/bin/libtool ${2}/libstdc++-v3
  make ${MAKE_J} ${MAKEOPT} || make ${MAKEOPT} || return 1
  make DESTDIR=${GCCBOOTDEST} install || return 1

  #Setup some missing bits
  if [ -e ${SRCDIR}/gcc/${GCC}/.build-info/post-install ];then
    sh ${SRCDIR}/gcc/${GCC}/.build-info/post-install ${1} ${SRCDIR}/gcc/${GCC} ${GCCBOOTDEST}
  fi;

#Build javac
#gcj -Wl,-Bsymbolic -findirect-dispatch --main=org.eclipse.jdt.internal.compiler.batch.Main \
#    /usr/share/java/ecj-3.5.2.jar -o ${3}/usr/bin/javac 
#x86_64-linux-gnu-gcj -mx32 -Wl,-Bsymbolic -findirect-dispatch --main=org.eclipse.jdt.internal.compiler.batch.Main
#/usr/share/java/ecj-3.5.2.jar -L/dist/build/x86_64/gcc-git/usr/libx32 -lgcj -lgcj_bc -o /usr/bin/javac-x3
  
  if [ "${1}" == "${TARCH}" ];then
    ln -s gcc ${GCCBOOTDEST}/usr/bin/cc
    tar_package ${GCCBOOTDEST} ${TOOLPKG}/${TARCH} ${TARGPKG} > /dev/null 2>&1
    #Fill the gap till full gcc built
    if [ "${TARCH}" == "${NARCH}" ] && [ ! -e ${STATDIR}/${TARCH}/done/gcc ];then
      rsync -aP ${GCCBOOTDEST}/ /
      if [ "${4}" == "shared" ];then
        (rm ${STATDIR}/${1}/done/gmp ${STATDIR}/${1}/done/mpfr ${STATDIR}/${1}/done/mpc \
            /usr/${NLIBDIR}/libgmp.a /usr/${NLIBDIR}/libgmpxx.a /usr/${NLIBDIR}/libppl.a \
            /usr/${NLIBDIR}/libppl_c.a /usr/${NLIBDIR}/libpwl.a /usr/${NLIBDIR}/libisl.a \
            /usr/${NLIBDIR}/libcloog-isl.a) >/dev/null 2>&1
      fi;
    fi;
   else
    tar_package ${GCCBOOTDEST} ${TOOLPKG}/${TARCH}/${1} ${TARGPKG} > /dev/null 2>&1
    if [ "${TARCH}" == "${NARCH}" ];then
      #Install if there is no existing compiler or im the cross
      if [ ! -e /usr/bin/${2}-gcc ] || [ "${4}" == "cross" ];then
        rsync -aP ${GCCBOOTDEST}/ /
        if [ "${4}" != "cross" ];then
          touch /usr/bin/${2}-gcc.${4}
         else
          for stamp in null boot multi shared;do
            if [ -e /usr/bin/${2}-gcc.${stamp} ];then
              rm /usr/bin/${2}-gcc.${stamp}
            fi;
          done
        fi;
       elif [ -e /usr/bin/${2}-gcc.null ] && [ "${4}" == "boot" ];then
        rsync -aP ${GCCBOOTDEST}/ /
        touch /usr/bin/${2}-gcc.boot
        rm /usr/bin/${2}-gcc.null
       elif [ -e /usr/bin/${2}-gcc.boot ];then
        if [ "${4}" == "multi" ] && [ ! -e /usr/bin/${2}-gcc.shared ];then
          rsync -aP ${GCCBOOTDEST}/ /
          touch /usr/bin/${2}-gcc.${4}
         elif [ "${4}" == "shared" ];then
          rsync -aP ${GCCBOOTDEST}/ /
          touch /usr/bin/${2}-gcc.${4}
        fi; 
      fi;
    fi;
  fi;
  return 0
}

build_qemu_static() {
  eval `cat ${DEFDIR}/qemu`;
  AVER=VERSION_${NARCH}
  VERSION=${!AVER-$VERSION}
  QEMU=qemu${VERSEP}${VERSION}

  DIST_PKG=${TOOLPKG}/${NARCH}/${QEMU}-static.tar.xz
  if [ -d ${TOOLDIR}/${NARCH}/${QEMU} ] && [ -f ${DIST_PKG} ];then
    return
  fi;
  svn_load_pkg qemu ${QEMU}

  (svn_load_pkg qemu ${QEMU}) || return 1
  setup_build_dir ${NARCH} qemu ${QEMU} ${NARCH}

  run_configure ${NLIBDIR} --static --disable-system --disable-user --enable-linux-user \
                --target-list=arm-linux-user,mips-linux-user,ppc-linux-user,ppc64-linux-user || return 1
  make ${MAKE_J} || make || return 1

  mkdir -p ${TOOLDIR}/${NARCH}/${QEMU}/usr/bin
  for arch in arm mips ppc ppc64;do
    uemu=${arch}-linux-user/qemu-${arch};
    cp ${uemu} ${TOOLDIR}/${NARCH}/${QEMU}/usr/bin/qemu-${arch}-static
  done

  rsync -aP ${TOOLDIR}/${NARCH}/${QEMU}/ /
  (cd ${TOOLDIR}/${NARCH}/${QEMU};tar -cJf ${DIST_PKG} *)
}

build_packages() {
  DARCH=${1}
  shift

  for pkg in $@;do
    if [ ! -e ${STATDIR}/${DARCH}/done/${pkg} ];then
      #If we fail on 1st pass rebuild with no clean opt's
      if ! (CLEANOPT=distclean;build_project ${pkg} ${DARCH});then
        (unset CLEANOPT;build_project ${pkg} ${DARCH}) || return 1
      fi;
    fi;
  done;
}

build_static_tool() {
  eval `cat ${DEFDIR}/${4}`;
  AVER=VERSION_${1}
  VERSION=${!AVER-$VERSION}
  STATICTOOL=${4}${VERSEP}${VERSION}

  if [ -d ${TOOLDIR}/${1}/${STATICTOOL}-static ];then
    return
  fi;

  echo "Building ${4}"

  svn_load_pkg ${4} ${STATICTOOL} || return 0

  if [ -d ${SRCDIR}/${4}/${STATICTOOL}/build-${1}-static ];then
    rm -rf ${SRCDIR}/${4}/${STATICTOOL}/build-${1}-static
  fi;

  if [  "${4}" != "subversion" ];then
    ARCHOPTV=OPT_${1}
    ARCHOPT=${!ARCHOPTV}
   else
    ARCHOPT="--with-neon=/build/${1}/usr/ --with-apr-util=/build/${1}/usr/";
  fi;

  if [ "${CFGPTH}" ];then
    CFGPTH="/${CFGPTH}"
   else
    CFGPTH="";
  fi;
  mkdir ${SRCDIR}/${4}/${STATICTOOL}${CFGPTH}/build-${1}-static 
  cd ${SRCDIR}/${4}/${STATICTOOL}${CFGPTH}/build-${1}-static

  run_configure ${3} --build=${BUILD} --host=${2} ${STATICOPT} ${ARCHOPT} || return 0

  if [ -x libtool ];then
    cp ${ARCHROOT}/${1}/usr/bin/libtool ./
  fi;

  #Texinfo hack
  for gnulib in gnulib/lib/ tools/gnulib/lib/;do
    if [ -d ${gnulib} ];then
      make -C ${gnulib}
    fi;
  done;

  if [ ! "${SYSROOTFIXUP}" ];then
    SYSROOTFIXUP="1";
  fi;
  export SYSROOTFIXUP;
  sysroot_fixup ${1}

  #Postconfig hook
  if [ -e ${SRCDIR}/${4}/${STATICTOOL}/.build-info/post-config ];then
    sh ${SRCDIR}/${4}/{STATICTOOL}/.build-info/post-config ${1} ${SRCDIR}/${4}/${STATICTOOL} ${TOOLDIR}/${1}/${STATICTOOL}-static
  fi;

  make ${MAKE_J} ${STATICMOPT} || make ${STATICMOPT} || return 0
  make DESTDIR=${TOOLDIR}/${1}/${STATICTOOL}-static install

  #Postinstall hook
  if [ -e ${SRCDIR}/${4}/${STATICTOOL}/.build-info/post-install ];then
    sh ${SRCDIR}/${4}/${STATICTOOL}/.build-info/post-install ${1} ${SRCDIR}/${4}/${STATICTOOL} ${TOOLDIR}/${1}/${STATICTOOL}-static
  fi;

  if [ "${STATICINSTLIBS}" ] && [ "${STATICINSTLIBS}" == "1" ];then
    if [ -d ${ARCHROOT}/${1} ];then
      rsync -avP ${TOOLDIR}/${1}/${STATICTOOL}-static/usr/${3}/*.a ${ARCHROOT}/${1}/usr/${3}/
     else
      rsync -avP ${TOOLDIR}/${1}/${STATICTOOL}-static/usr/${3}/*.a /usr/${3}/
    fi;
  fi;

  tar_package ${TOOLDIR}/${1}/${STATICTOOL}-static ${TOOLPKG}/${1} ${STATICTOOL}-static > /dev/null 2>&1
}

static_toolbuild() {
  if [ "${1}" != "${NARCH}" ];then
    arch_config ${1}
    TLIBDIR=${SETLIBDIR}
    TARGET=${TUPPLE}
   else
    TLIBDIR=${NLIBDIR}
    TARGET=${BUILD}
  fi;
  for stool in bison flex sed gawk bash make coreutils nano rsync grep less gzip tar xz texinfo \
      pkg-config util-linux m4 cpio diffutils libtool gperf krb5 subversion;do
    (build_static_tool ${1} ${TARGET} ${TLIBDIR} ${stool})
  done;
}

build_toolchain() {
  #Is LD good ?? create symlinks needed
  for bintool in `ls /usr/${2}/bin/`;do
    if [ ! -e /usr/bin/${2}-${bintool} ];then
      ln -s ../${2}/bin/${bintool} /usr/bin/${2}-${bintool};
    fi;
  done

  #Build fresh glibc we are asuming that binutils/gcc/make/bash/sed/awk are good as they should be
  (build_glibc ${1} ${2}) || return 1

  #Build perl/autoconf/zlib and Libs needed for GCC
  (build_packages ${1} groff perl automake-1.9 automake-1.10 automake-1.11 automake-1.12 automake-1.13 help2man autoconf \
                       zlib libtool gmp mpfr mpc) || return 1

  #GCC C build to bootstrap multiarch
  case ${1} in
    x86_32)(build_gcc_bootstrap ${1} ${2} ${1} multi) || return 1;
           (build_glibc i686 i686-linux-gnu) || return 1;
           (build_glibc x86_64 x86_64-linux-gnu) || return 1;;
    x86_64)(build_gcc_bootstrap ${1} ${2} ${1} multi) || return 1;
           (build_glibc i686 i686-linux-gnu) || return 1;
           (build_glibc x86_32 x86_64-linux-gnux32) || return 1;;
  esac

  #Shared GCC / Multi arch C/C++
  (build_gcc_bootstrap ${1} ${2} ${1} shared) || return 1

  #Rebuild libtool this will be rebuilt again after final GCC build
  if [ ! -e ${STATDIR}/${1}/done/gcc ] && [ -e ${STATDIR}/${1}/done/libtool ];then
    rm ${STATDIR}/${1}/done/libtool 
    (build_packages ${1} libtool) || return 1
    rm ${STATDIR}/${1}/done/libtool
  fi;

  #Build GCC
  (build_packages ${1} gmp mpfr mpc isl cloog zip unzip gcc libtool) || return 1

  #Base dependancies
  (build_packages ${1} gperf libcroco gettext make sed ncursesw ncurses texinfo zlib binutils libsigsegv gawk m4 \
                       bison diffutils flex attr acl pcre libsepol libselinux file gengetopt libidn libtasn1 p11-kit \
                       nettle gnutls libgpg-error libgcrypt libprelude libtirpc Linux-PAM libcap coreutils \
                       readline bash xz expat) || return 1

  #Dont build libxml2 if there is a python in / may not be one in /build/.../
  if [ ! -d /usr/lib/python2.7 ];then
    (build_packages ${1} libxml2 libxslt) || return 1
  fi;

  #Add required perl modules from cpan may not need libxml only expat !!!
  for pmod in XML::Parser XML::SAX Font::TTF;do
    if [ ! -e ${STATDIR}/${1}/done/${pmod} ];then
      cpan -i ${pmod} && touch ${STATDIR}/${1}/done/${pmod}
    fi;
  done

  if [ ! -e ${STATDIR}/${1}/done/gcc ] && [ -e ${STATDIR}/${1}/done/libtool ];then
    rm ${STATDIR}/${1}/done/libtool
    (build_packages ${1} libtool) || return 1
    rm ${STATDIR}/${1}/done/libtool
  fi;

  if [ ! -e ${STATDIR}/${1}/done/Python ] && [ -e ${STATDIR}/${1}/done/libxml2 ];then
    rm ${STATDIR}/${1}/done/libxml2
  fi;

  if [ ! -e ${STATDIR}/${1}/done/Python ] && [ -e ${STATDIR}/${1}/done/libxslt ];then
    rm ${STATDIR}/${1}/done/libxslt
  fi;

  (build_packages ${1} intltool popt rsync Python libxml2 libxslt gnome-doc-utils docbook-4.1.2 docbook-4.2 \
                       docbook-4.3 docbook-4.4  docbook-4.5 docbook-xsl scrollkeeper which libffi dbus glib gtk-doc \
                       pkg-config libassuan libksba pth libusb libusb-compat gnupg openssl trousers slang \
                       gobject-introspection vala gengetopt wget) || return 1

  if [ ! -e ${STATDIR}/${1}/done/util-linux ];then
    rm /usr/lib64/libblkid.a /usr/lib64/libuuid.a /usr/lib64/libblkid.la /usr/lib64/libuuid.la >/dev/null 2>&1
  fi;

  (build_packages ${1} util-linux nano rsync grep less gzip tar pkg-config cpio iana-etc xmlto xmltoman giflib freetype \
                       fontconfig fonttools lcms2 jpeg libpng openjpeg libmng OpenSP c-ares curl git) || return 1

  #This will fail due to Mesa so dont bail only do it on first pass use build_project directly
  if [ ! -e ${STATDIR}/${1}/fail/Xorg ] && [ ! -e ${STATDIR}/${1}/done/Xorg ];then
    (CLEANOPT=distclean;build_project Xorg ${1}) || touch ${STATDIR}/${1}/fail/Xorg
  fi;

  (build_packages ${1} cairo pango libdrm llvm intltool cmake talloc tevent libevent libverto krb5 cups kmod \
                       module-init-tools LVM2 cryptsetup systemd Mesa glu glw mtdev) || return 1

  #Continue X Build with GL/Mesa
  if [ -e ${STATDIR}/${1}/fail/Xorg ] && [ ! -e ${STATDIR}/${1}/done/Xorg ];then
    (unset CLEANOPT;build_project Xorg ${1}) || return 1
  fi;

  (build_packages ${1} fontforge freeglut pcsc-lite tiff atk  gdk-pixbuf gtk+ patch alsa-lib fastjar icedtea6 icedtea7 \
                       yasm nasm fuse libunistring txt2man printproto portablexdr libpcap ppp libIDL ORBit2 dbus-glib \
                       polkit GConf libbonobo gc guile libmad Xaw3d gv polkit-gnome rtmpdump swig M2Crypto libnl-1 libnl \
                       crda ragel apr apr-iconv sqlite-autoconf keyutils neon apache-ant tcl8 tk8 db unixODBC \
                       cyrus-sasl openslp openldap mysql postgresql apr-util httpd subversion libva gavl OpenCV \
                       frei0r libraw1394 audiofile esound libogg flac libvorbis libsndfile gdbm json-c fftw \
                       libsamplerate speex orc pulseaudio SDL libdc1394 libavc1394 libiec61883 faac libaacplus \
                       vo-aacenc vo-amrwbenc fribidi icu4c graphite2 harfbuzz libass libbluray celt libcaca gsm \
                       libmodplug lame twolame libnut opencore-amr opus schroedinger libtheora utvideo openal xvidcore \
                       ptlib libcddb libcdio-cdda libcdio libcddb fltk libdaemon libnfnetlink libmnl libexif exif \
                       libnetfilter_conntrack libnetfilter_cttimeout ilmbase gss librsvg iptables usbutils \
                       xavs x264 libvpx v4l-utils fdk-aac ffmpeg h323plus gnugk t38modem bzip2 qt-4 avahi gnome-vfs \
                       gstreamer libvisual gst-plugins-base qt-4 djvulibre) || return 1
  #Time to build a static gcc bootstrap distributable
  (build_gcc_bootstrap ${1} ${2} ${1} static) || return 1

  #Static binutils distributable
  (build_bootstrap_binutils ${1} ${2}) || return 1

  #Build tools needed for compiling
  static_toolbuild ${1} ${2}
}

build_cross_package() {
  #Check arch build dir exists Setup linux headers and env vars
  check_create_arch ${1}
  if [ ! -d ${TOOLPKG}/${NARCH} ];then
    mkdir -p ${TOOLPKG}/${NARCH}
  fi;

  #dont build cross tools for native but ensure toolchain is good
  if [ "${1}" == "${NARCH}" ];then
    build_toolchain ${NARCH} ${BUILD} || return 1

    #QEMU Static runtime emulator
    (build_qemu_static) || return 1
    return;
  fi;

  case ${1} in
    #Multi arch/lib for intel i686 does not support it
    x86_32|x86_64)
      case ${NARCH} in
        x86_32|x86_64)
          #Add Arch bootstrap GCC this is not actually used its a distributable
          (if [ "${1}" == "x86_32" ];then
            MOPT="-mx32";
           else
            MOPT="-m64";
          fi;
          export CC="${BUILD}-gcc ${MOPT} --sysroot=${ARCHROOT}/${1}"
          build_gcc_bootstrap ${1} ${HOST} ${1} static) || return 1

          #Setup GLIBC For x86 ABI
          (build_glibc ${1} ${HOST}) || return 1

          return
        ;;
      esac
    ;;
  esac;

  #Here we build a cross chain for non native / multarch
  if [ ! -d ${TOOLPKG}/${NARCH}/${1} ];then
    mkdir -p ${TOOLPKG}/${NARCH}/${1}
  fi;

  #Binutils to handle the target
  (build_bootstrap_binutils ${1} ${HOST}) || return 1

  #Null compiler to bootstrap GLIBC
  (build_gcc_bootstrap ${1} ${HOST} ${NARCH} null) || return 1;

  #GLIBC
  (build_glibc ${1} ${HOST}) || return 1;

  #Static compiler to bootstrap GLIBC distributed static with C++/ADA
  (build_gcc_bootstrap ${1} ${HOST} ${NARCH} static) || return 1;

  #Cross compiler
  (build_gcc_bootstrap ${1} ${HOST} ${NARCH} cross) || return 1;

  #Add QEMU static to build
  if [ -d ${ARCHROOT}/${1}/usr/bin ] && [ "${QCPU}" ] && [ -f ${TOOLDIR}/${NARCH}/${QEMU}/usr/bin/qemu-${QCPU}-static ];then
    if [ ! -f ${ARCHROOT}/${1}/usr/bin/qemu-${QCPU}-static ] || \
       [ ${TOOLDIR}/${NARCH}/${QEMU}/usr/bin/qemu-${QCPU}-static -nt ${ARCHROOT}/${1}/usr/bin/qemu-${QCPU}-static ];then
      cp ${TOOLDIR}/${NARCH}/${QEMU}/usr/bin/qemu-${QCPU}-static ${ARCHROOT}/${1}/usr/bin/qemu-${QCPU}-static
    fi;
  fi;

  build_toolchain ${1} ${HOST} || return 1

return 0;
exit
#--gn
#  if [ ! -e ${ARCHROOT}/${1}/usr/${B_LIBDIRS}/libc.so ] || [ ! -d ${TOOLDIR}/${1}/${GLIBC} ];then
#We need to make sure the multi arch libs are inplace before building the compiler
#   case ${1} in
#     powerpc64)
#       #Need stubs-32.h from 32bit
#       rsync -aP ${TOOLDIR}/powerpc/${GLIBC}/usr/include/gnu/stubs-32.h ${ARCHROOT}/${1}/usr/include/gnu/
#
#       #Add the 32bit libs to 64bit for sysroot
#       rsync -aP ${TOOLDIR}/powerpc/${GLIBC}/lib ${ARCHROOT}/${1}/
#       rsync -aP ${TOOLDIR}/powerpc/${GLIBC}/usr/lib ${ARCHROOT}/${1}/usr/
#     ;;
#     mips64)
#       #Need stubs-o32.h from 32bit
#       rsync -aP ${TOOLDIR}/mips/${GLIBC}/usr/include/gnu/stubs-o32.h ${ARCHROOT}/${1}/usr/include/gnu/
#
#       #Add the 32bit libs to 64bit for sysroot
#       rsync -aP ${TOOLDIR}/mips/${GLIBC}/lib ${ARCHROOT}/${1}/
#       rsync -aP ${TOOLDIR}/mips/${GLIBC}/usr/lib ${ARCHROOT}/${1}/usr/
#     ;;
#    esac;
#    #Sync to build sysroot
#    if [ ! -e ${ARCHROOT}/${1}/usr/${B_LIBDIRS}/libc.so ];then
#      rsync -aP ${TOOLDIR}/${1}/${GLIBC}/ ${ARCHROOT}/${1}/
#    fi;
#  fi;
}

configstatdir() {
  if [ ! -d ${STATDIR} ];then
    mkdir ${STATDIR}
  fi;

  if [ ! -d ${STATDIR}/${1} ];then
    mkdir ${STATDIR}/${1}
  fi;
  for stat in done fail output;do
    if [ ! -d ${STATDIR}/${1}/${stat} ];then 
      mkdir ${STATDIR}/${1}/${stat}
    fi;
  done
}

failpkg() {
  touch ${STATDIR}/${2}/fail/${1}
}

loop_on_dir() {
  configstatdir ${1}
  for pkg in `ls ${DEFDIR}`;do
    if [ -e ${STATDIR}/${1}/done/${pkg} ];then
      continue;
    fi;
    (if check_package ${pkg};then
      build_project ${pkg} ${1} || failpkg ${pkg} ${1}
    fi;)
  done;

  if [ -e ${STATDIR}/${1}/change ];then
    rm ${STATDIR}/${1}/change;
    return 0;
   else
    return 1;
  fi;
}

buildall_arch() {
  while loop_on_dir ${1};do
    if [ -e ${STATDIR}/${1}/change ];then
      rm ${STATDIR}/${1}/change
    fi;
  done;
}

if [ ! -d /dist/def ] || [ ! -d /dist/scripts ];then
  svn co ${SVNBASE}/buildscripts/trunk/ /dist/
fi;

#XXX find packages smarter use svn
for pkg in binutils gcc glibc qemu;do
  if [ ! -e ${DEFDIR}/${pkg} ];then
    echo "Missing cross build definitions requires binutils gcc glibc";
    exit 1;
  fi;
done;

#Setup Native enviroment doing it like this prevents code replication
arch_config ${NARCH}
BUILD=${TUPPLE}
NLIBDIR=${SETLIBDIR}
NKARCH=${LINARCH}
unset TUPPLE SETLIBDIR LINARCH
export BUILD NKARCH NLIBDIR

#OpenJDK specifically barfs when these are not inplace check and fix
for binlink in cpio tar sed grep fgrep egrep;do
  if [ ! -e /bin/${binlink} ] && [ -x /usr/bin/${binlink} ];then
    ln -s /usr/bin/${binlink} /bin;
  fi;
done

if [ -d /usr/share/java ] && [ -d ${PKGDISTDIR} ] && [ ! -f ${PKGDISTDIR}/java-jar.tar.xz ];then
  find /usr/share/java/ ! -regex .*libgcj.* |cpio -ov -H tar |xz -9 > ${PKGDISTDIR}/java-jar.tar.xz
fi;

for barch in ${ARCHLIST};do
  #Setup stat dir
  configstatdir ${barch}

  #ensure the tool chain is in place
  build_cross_package ${barch} || continue;

  #Build multiple packages XXX add svn bits
  if (( $# > 1 ));then
    for bproject in $@;do
      if check_package ${bproject};then
        (build_project ${bproject} ${barch} || failpkg ${bproject} ${barch})
      fi;
    done;
   elif (( $# == 1 ));then
    if [ ${1} == "buildall" ];then
       (buildall_arch ${barch})
     elif check_package ${1};then
      (build_project ${1} ${barch} || failpkg ${1} ${barch})
    fi;
   else
    (buildall_arch ${barch})
  fi;
done;
