#!/bin/bash

PDEF=/dist/def/
ARCHS="i686 x86_32 x86_64 arm mips mips64 powerpc powerpc64";

for pkg in `ls ${PDEF}`;do
  (eval `cat ${PDEF}/${pkg}`
  if [ "${ALIAS}" ];then
    SDIR=${ALIAS}
   else
    SDIR=${pkg}
  fi;
  SDIR=${SDIR}/${SDIR}${VERSEP}${VERSION}
  for barch in ${ARCHS};do
    if [ -d  /usr/src/${SDIR}/build-${barch} ];then
      rm -rf /usr/src/${SDIR}/build-${barch}
    fi;
  done;
  make -C /usr/src/${SDIR} clean distclean
  )
done;
