#!/bin/bash

unset CFLAGS CXXFLAGS CC

ARCHT="x86_64-linux-gnu x86_64-linux-gnux32 i686-linux-gnu \
       powerpc-linux-gnu powerpc64-linux-gnu arm-linux-gnueabi";

for acpp in ${ARCHT};do
  touch /usr/bin/${acpp}-g++
done

sh ./bootstrap.sh

./b2 gcc-${1}

if true;then
  if [ ! -d ${3}/usr/${B_LIBDIRS} ];then
    mkdir -p ${3}/usr/${B_LIBDIRS}
  fi;
  if [ ! -d ${3}/usr/include ];then
    mkdir -p ${3}/usr/include
  fi;
  rsync -avP stage/lib/ ${3}/usr/${C_LIBDIRS}/
  rsync -avP boost ${3}/usr/include/
fi;

for acpp in ${ARCHT};do
  if [ ! -s /usr/bin/${acpp}-g++ ];then
    rm /usr/bin/${acpp}-g++
  fi;
done;
