#!/bin/bash

unset CFLAGS LDFLAGS CC CXX CPPFLAGS CXXFLAGS LD

if [ "${1}" == "${NARCH}" ] && [ ! -d /build/${1} ];then
  mkdir -p /opt/qt-${QT_VER}/${B_LIBDIRS}
 else
  mkdir -p /build/${1}/opt/qt-${QT_VER}/${B_LIBDIRS}
fi;

#Possible rebuild
if [ -e Makefile.build ];then
  mv Makefile.build Makefile
fi;

#Initialise modules and configure
if [ "${4}" ] || [ ! -e Makefile ];then
  if [ -e .gitmodules ];then
    git submodule foreach --recursive "git clean -dfx"
    git submodule deinit -f .
   else
    make confclean ${4}
  fi;
  ./init-repository
  if [ "${1}" == "x86_32" ];then
    git submodule deinit -f qtjsbackend qtscript
  fi;
  ./configure ${CONFOPT} -xplatform ${QT_SPEC} -platform ${QT_HOSTSPEC} || exit 1
fi;

#make sure index is build with correct ranlib
if [ "${1}" != "${NARCH}" ];then
  if [ -d qtbase/lib ];then
    make ${MAKE_J} all || rm qtbase/lib/libQt5Bootstrap.a
    make ${MAKE_J} -C qtbase/src/tools/bootstrap RANLIB=${BUILD}-ranlib
   elif [ -d src/tools/bootstrap ];then
    make ${MAKE_J} all || rm src/tools/bootstrap/libbootstrap.a
    make ${MAKE_J} -C src/tools/bootstrap RANLIB=${BUILD}-ranlib
  fi;
fi;

make ${MAKE_J} RANLIB=${BUILD}-ranlib all || make RANLIB=${BUILD}-ranlib || exit 1
make INSTALL_ROOT=${3} install || exit 1

#stop diet clean cleaning up
mv Makefile Makefile.build
