#!/bin/bash

unset CFLAGS CXXFLAGS CC

for acpp in x86_64-linux-gnu x86_64-linux-gnux32 i686-linux-gnu;do
  touch /usr/bin/${acpp}-g++
done

sh ./bootstrap.sh

./b2 gcc-${1}

if true;then
  if [ ! -d ${3}/usr/${B_LIBDIRS} ];then
    mkdir -p ${3}/usr/${B_LIBDIRS}
  fi;
  if [ ! -d ${3}/usr/include ];then
    mkdir -p ${3}/usr/include
  fi;
  rsync -avP stage/lib/ ${3}/usr/${B_LIBDIRS}/
  rsync -avP boost ${3}/usr/include/
fi;

for acpp in x86_64-linux-gnu x86_64-linux-gnux32 i686-linux-gnu;do
  if [ ! -s /usr/bin/${acpp}-g++ ];then
    rm /usr/bin/${acpp}-g++
  fi;
done;
