#!/bin/bash

pkg=nss-3.13.6


#for arch in i686 arm x86_64;do
for arch in i686;do
  cd /usr/src/${pkg}/mozilla/security/nss

  if [ "${arch}" == "arm" ];then
    HOST="arm-embed-linux-gnueabi";
   else
    HOST="${arch}-pc-linux-gnu";
  fi;

  DESTDIR=/dist/${arch}/${pkg}/

  make clobber
  rm -rf ../../dist/Linux3.4_x86_*
  make nss_build_all BUILD_OPT=1 NSPR_INCLUDE_DIR=/usr/include/nspr/ USE_SYSTEM_ZLIB=1 \
	ZLIB_LIBS=-lz NSS_USE_SYSTEM_SQLITE=1 CXX=${HOST}-g++  CC=${HOST}-gcc NATIVE_CC=gcc \
	CROSS_COMPILE=1 LD=${HOST}-ld AR="${HOST}-ar r" RANLIB=${HOST}-ranlib clobber

  make nss_build_all BUILD_OPT=1 NSPR_INCLUDE_DIR=/usr/include/nspr/ USE_SYSTEM_ZLIB=1 \
	ZLIB_LIBS=-lz NSS_USE_SYSTEM_SQLITE=1 CXX=${HOST}-g++  CC=${HOST}-gcc NATIVE_CC=gcc \
	CROSS_COMPILE=1 LD=${HOST}-ld AR="${HOST}-ar r" RANLIB=${HOST}-ranlib clobber nss_build_all

  mkdir -p ${DESTDIR}/usr/lib ${DESTDIR}/usr/include/nss ${DESTDIR}/usr/bin

  cd ../../dist &&
  install -v -m755 Linux*/lib/*.so ${DESTDIR}/usr/lib              &&
  install -v -m644 Linux*/lib/{*.chk,libcrmf.a} ${DESTDIR}/usr/lib &&
  install -v -m755 -d ${DESTDIR}/usr/include/nss                   &&
  cp -v -RL {public,private}/nss/* ${DESTDIR}/usr/include/nss      &&
  chmod 644 ${DESTDIR}/usr/include/nss/*                           &&
  install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} ${DESTDIR}/usr/bin &&
  install -v -m644 Linux*/lib/pkgconfig/nss.pc ${DESTDIR}/usr/lib/pkgconfig
done
