#!/bin/bash

#${barch} ${HOST} ${DIST_ROOT} ${CLEANOPT} 

unset CFLAGS LDFLAGS CC CXX CPPFLAGS CXXFLAGS LD

if [ "${4}" ];then
  make confclean ${4}
fi;

if [ "${1}" == "${NARCH}" ] && [ ! -d /build/${1} ];then
  mkdir -p /opt/qt-4/${B_LIBDIRS}
 else
  mkdir -p /build/${1}/opt/qt-4/${B_LIBDIRS}
fi;

ARCH="";
case ${1} in
	i686)PLATFORM=linux-g++-32;;
	mips)PLATFORM=linux-mips-g++;
		ARCH="-host-arch mips";;
	mips64)PLATFORM=linux-mips-g++-64;
		ARCH="-host-arch mips";;
	arm)PLATFORM=linux-arm-gnueabi-g++;
		ARCH="-host-arch arm";;
	powerpc)PLATFORM=linux-ppc-g++;
		ARCH="-host-arch powerpc";;
	powerpc64)PLATFORM=linux-ppc-g++-64;
		ARCH="-host-arch powerpc";;
	x86_64)PLATFORM=linux-g++-64;;
	x86_32)PLATFORM=linux-g++-x32;;
esac;

export QMAKE_INCDIR_X11="-I=/usr/X11R7/include";
export QMAKE_LIBDIR_X11="-L=/usr/X11R7/${B_LIBDIRS}";

./configure -prefix /opt/qt-4 -v -opensource -openssl-linked -confirm-license -xplatform ${PLATFORM} \
            -no-javascript-jit -no-scripttools -no-webkit -no-script -libdir /opt/qt-4/${B_LIBDIRS} ${ARCH}
make -C src/tools/bootstrap all ;ranlib src/tools/bootstrap/libbootstrap.a
make -j6 INSTALL_ROOT=${3} all && make INSTALL_ROOT=${3} install
