#!/bin/bash

NARCH=`uname -m`

export PREFIX=/usr/X11R7
if [ "${1}" == "${NARCH}" ] && [ ! -d /build/${1} ];then
  DESTDIR=/
 else
  DESTDIR=/build/${1}/
fi;
export DESTDIR
export DPATH=${DESTDIR}${PREFIX}
export MAKEFLAGS=${MAKE_J}


export LD_LIBRARY_PATH=/usr/${B_LIBDIRS}:/${B_LIBDIRS}:${SYSROOT}/${B_LIBDIRS}:${SYSROOT}/usr/${B_LIBDIRS}:${SYSROOT}/${PREFIX}/${B_LIBDIRS}

if [ "${4}" ];then
  ./util/modular/build.sh -L |grep -vE "(^driver/xf86-video-newport)|(^driver/xf86-video-sis)|(^mesa)" > tobuild
  cat tobuild |awk '{printf "make -C %s distclean\n",$1}' |sh
fi;

if [ "${NARCH}" == "x86_64" ];then
  case ${1} in
    i686|x86_32|x86_64)BUILD=${2};;
  esac;
fi;

#set
#exit -1


if [ ! -d ${DPATH} ];then
  mkdir -p ${DPATH}
fi;

export CC_FOR_BUILD=gcc
export CXX_FOR_BUILD=g++
export CONFFLAGS="--host=${2} --build=${BUILD} --with-sysroot --libdir=${PREFIX}/${B_LIBDIRS}"

export CXXFLAGS_FOR_BUILD="-L/usr/lib"
export CFLAGS_FOR_BUILD=-I.
export LDFLAGS_FOR_BUILD=-L.

./util/modular/build.sh --modfile ./tobuild ${PREFIX}

if [ ! -d ${3}/${PREFIX} ];then
  mkdir -p ${3}/${PREFIX}
fi;
rsync -avP ${DESTDIR}${PREFIX}/ ${3}/${PREFIX}/
