#!/bin/bash

FILTER_arm="|(driver/xf86-input-vmmouse)|(driver/xf86-video-intel)";
FILTER_arm64="|(driver/xf86-input-vmmouse)|(driver/xf86-video-intel)|(data/cursors)|(font/)";
FILTER_mips="|(driver/xf86-input-vmmouse)|(driver/xf86-video-intel)";

FILT=FILTER_${1}
FILTER=${!FILT}

OPT_mips="--disable-loongson-mmi";
AOPT=OPT_${1}
ARCHOP=${!AOPT}

sync_fin() {
  if [ ! -d ${1}/${PREFIX} ];then
    mkdir -p ${1}/${PREFIX}
  fi;
  rsync -avP ${DESTDIR}${PREFIX}/ ${1}/${PREFIX}/

  #Clean up failed pkg
  if [ "${2}" ] && [ "${2}" == "1" ];then
    clean="";
    for pkg in `./util/modular/build.sh -L`;do
      if [ ! -e ${pkg}/config.log ] || [ ! -e tobuild ] || [ ./tobuild -nt ${pkg}/config.log ];then
        clean=${pkg};
      fi;
    done
    if [ "${clean}" ];then
      make -C ${clean} clean distclean
      rm ${clean}/config.log
    fi;
  fi;

  exit ${2}
}

NARCH=`uname -m`

export PREFIX=/usr/X11R7
if [ "${1}" == "${NARCH}" ] && [ ! -d /build/${1} ];then
  DESTDIR=/
 else
  DESTDIR=/build/${1}/
fi;
export DESTDIR PKG_CONFIG_PATH
export DPATH=${DESTDIR}${PREFIX}
export MAKEFLAGS=${MAKE_J}

export ACLOCAL="aclocal-1.11";
export AUTOMAKE="automake-1.11";

export LD_LIBRARY_PATH=/usr/${B_LIBDIRS}:/${B_LIBDIRS}:${SYSROOT}/${B_LIBDIRS}:${SYSROOT}/usr/${B_LIBDIRS}:${SYSROOT}/${PREFIX}/${B_LIBDIRS}

if [ ! -d ./util/modular ];then
  git clone git://anongit.freedesktop.org/git/xorg/util/modular util/modular
fi;

if [ "${4}" ];then
  ./util/modular/build.sh -L |awk '{printf "make -C %s distclean\n",$1}' |sh
  rm tobuild
fi;

(for pkg in `./util/modular/build.sh -L |grep -vE "(^driver/xf86-video-newport)|(^driver/xf86-video-sis)|(^mesa)${FILTER}"`;do
  if [ ! -e ${pkg}/config.log ] || [ ! -e tobuild ] || [ ./tobuild -nt ${pkg}/config.log ];then
    echo ${pkg};
  fi;
done) > tobuild.tmp
cp tobuild.tmp tobuild
touch tobuild

if [ "${NARCH}" == "x86_64" ];then
  case ${1} in
    i686|x86_32|x86_64)BUILD=${2};;
  esac;
fi;

if [ ! -d ${DPATH} ];then
  mkdir -p ${DPATH}
fi;

export CC_FOR_BUILD=gcc
export CXX_FOR_BUILD=g++
export CONFFLAGS="--host=${2} --build=${BUILD} --with-sysroot --libdir=${PREFIX}/${B_LIBDIRS} --disable-selective-werror 
                  ac_cv_file__dev_urandom=yes --with-utmp-file=/var/run/utmp --with-wtmp-file=/var/log/wtmp
                  ac_cv_file__usr_X11R7_include_xorg_dri_h=yes ac_cv_file__usr_X11R7_include_xorg_sarea_h=yes
                  ac_cv_file__usr_X11R7_include_xorg_dristruct_h=yes ac_cv_file__usr_X11R7_include_xorg_damage_h=yes"

export CXXFLAGS_FOR_BUILD="-L/usr/lib"
export CFLAGS_FOR_BUILD=-I.
export LDFLAGS_FOR_BUILD=-L.
export MANCONF="/etc/man.conf";

./util/modular/build.sh --clone --modfile ./tobuild ${PREFIX} || sync_fin ${3} 1

#LD Config
mkdir -p ${3}/etc/ld.so.conf.d
echo "/usr/X11R7/${B_LIBDIRS}" > ${3}/etc/ld.so.conf.d/xwin.conf
if [ "${1}" == "${NARCH}" ];then
  /sbin/ldconfig
fi;

sync_fin ${3} 0
