#!/bin/bash

if [ ! -e hostpython ] || [ ! -e hostpgen ];then
  ../configure --enable-shared
  make python Parser/pgen
  mv python hostpython
  mv Parser/pgen hostpgen
  make distclean
fi;

if [ ! -e Python-2.7.2-xcompile.patch ];then
  wget http://randomsplat.com/wp-content/uploads/2011/10/Python-2.7.2-xcompile.patch
  if [ -e Python-2.7.2-xcompile.patch ];then 
    patch -p1 < Python-2.7.2-xcompile.patch
   else 
    exit;
  fi;
fi;

/dist/scripts/pybuild nodir arm
/dist/scripts/pybuild nodir x86_64
/dist/scripts/pybuild nodir i686
