#!/bin/bash

GLIBCVER=2.18
QEMU=1.6.1
ANTVER=1.9.2

AUTOCONF=2.69
AUTOMAKE=1.9.6

DISTDIR=/dist
PKGDISTDIR=${DISTDIR}/pkg
CROSSDISTDIR=${DISTDIR}/cross

NARCH=$( uname -m )

case ${NARCH} in
  arm*)NARCH=arm;;
esac;

if [ "${1}" ];then
  DARCH=${1}
 else
  DARCH=${NARCH}
fi;

if [ ! "${DARCH}" ] || [ ! -d ${PKGDISTDIR}/build/${DARCH} ];then
  echo require arch
  exit;
fi;

case ${DARCH} in
  arm*)STRIP=arm-linux-gnueabi-strip;;
  arm64)STRIP=aarch64-linux-gnu-strip;;
  mips64)STRIP=mips64-linux-gnuabi64-strip;;
  x86_32)STRIP=x86_64-linux-gnux32-strip;;
  *)STRIP=${DARCH}-linux-gnu-strip;;
esac;

#Determine kernel arch
case ${DARCH} in
  x86_*|i[3-6]86)LINARCH="x86";;
  arm64)LINARCH=arm64;;
  *64)LINARCH=${DARCH::-2};;
  *)LINARCH=${DARCH};
esac;

if [ ${2} ];then
  STATICROOT=${2}
 else
  STATICROOT=${DISTDIR}/root/${DARCH}-static
fi;

if [ -d ${STATICROOT} ];then
  rm -rf ${STATICROOT}
fi;
mkdir -p ${STATICROOT}/etc
touch ${STATICROOT}/etc/.static

cd ${PKGDISTDIR}/build/${DARCH}
for pkg in `ls -d *static *boot` ;do
  for subpkg in `ls ${pkg}/${pkg}.tar.xz ${pkg}/${pkg}-libs.tar.xz ${pkg}/${pkg}-dev.tar.xz 2>/dev/null`;do
    tar --exclude=*/.dbg/* -C ${STATICROOT} -xJf ${subpkg};
  done;
done

if [ -e ${CROSSDISTDIR}/${NARCH}/qemu-${QEMU}/usr/bin/qemu-${DARCH}-static ];then
  cp ${CROSSDISTDIR}/${NARCH}/qemu-${QEMU}/usr/bin/qemu-${DARCH}-static ${STATICROOT}/usr/bin
fi;

#Strip all the bits
${STRIP} ${STATICROOT}/bin/* ${STATICROOT}/sbin/* ${STATICROOT}/usr/bin/* ${STATICROOT}/usr/sbin/*

for devpkg in ${PKGDISTDIR}/${DARCH}/glibc-${GLIBCVER}/glibc-${GLIBCVER}-dev.tar.xz \
              ${PKGDISTDIR}/${DARCH}/glibc-${GLIBCVER}/glibc-${GLIBCVER}-libs.tar.xz \
              ${PKGDISTDIR}/${DARCH}/glibc-${GLIBCVER}/glibc-${GLIBCVER}-conf.tar.xz \
              ${PKGDISTDIR}/${DARCH}/glibc-${GLIBCVER}/glibc-${GLIBCVER}.tar.xz \
              ${PKGDISTDIR}/${DARCH}/apache-ant-${ANTVER}/apache-ant-${ANTVER}-libs.tar.xz \
              ${PKGDISTDIR}/${DARCH}/autoconf-${AUTOCONF}/autoconf-${AUTOCONF}.tar.xz \
              ${PKGDISTDIR}/${DARCH}/automake-${AUTOMAKE}/automake-${AUTOMAKE}.tar.xz \
              kernel-headers.tar.xz ${PKGDISTDIR}/java-jar.tar.xz;do
  if [ -f ${devpkg} ];then
    tar --exclude=*/.dbg/* -C ${STATICROOT} -xJf ${devpkg};
  fi;
done;

if [ ! -e ${STATICROOT}/usr/include/asm ];then
  ln -s asm-${LINARCH} ${STATICROOT}/usr/include/asm
fi;

for sysdir in proc sys dev root tmp usr/src dist etc/xml;do
  mkdir -p ${STATICROOT}/${sysdir}
done;

rsync -avP ${DISTDIR}/res ${STATICROOT}/

for mdir in 1 2 3 4 5 6 7 8;do
  mkdir -p ${STATICROOT}/usr/share/man/man${mdir}
done;

#Install terminfo DB / Stub files / CPAN config
if [ -d /usr/share/terminfo ];then
  rsync -avRP /usr/share/terminfo ${STATICROOT}/
fi;
if [ -d /lib/terminfo ];then
  rsync -avRP /lib/terminfo ${STATICROOT}/
fi;
rsync -avRP /usr/include/gnu/stubs-* /usr/share/terminfo ${STATICROOT}/

if [ ! -e /root/.cpan/CPAN/MyConfig.pm ];then
  cpan -i XML::Parser
fi

if [ -e /root/.cpan/CPAN/MyConfig.pm ];then
  rsync -aR /root/.cpan/CPAN/MyConfig.pm ${STATICROOT}/
fi;

echo "nameserver ::1" > ${STATICROOT}/etc/resolv.conf
if [ -e ${STATICROOT}.sqfs ];then
  rm ${STATICROOT}.sqfs
fi;

mkdir ${STATICROOT}/build
ln -s ..  ${STATICROOT}/build/${DARCH}

chroot ${STATICROOT} /sbin/ldconfig

mksquashfs ${STATICROOT}/* ${STATICROOT}.sqfs -comp xz
