#!/bin/bash

GLIBCVER=2.17

NARCH=$( uname -m )

if [ ! "${NARCH}" ] || [ ! -d /dist/pkg/build/${NARCH} ];then
  echo require arch
  exit;
fi;

STATICROOT=/dist/root/${NARCH}-static

if [ -d ${STATICROOT} ];then
  rm -rf ${STATICROOT}
fi;
mkdir -p /dist/root/${NARCH}-static

cd /dist/pkg/build/${NARCH}
for pkg in `ls -d *static *boot` ;do
  for subpkg in `ls ${pkg}/${pkg}.tar.xz ${pkg}/${pkg}-dev.tar.xz ${pkg}/${pkg}-libs.tar.xz 2>/dev/null`;do
    tar -C ${STATICROOT} -xJf ${subpkg};
  done;
done
for devpkg in glibc-${GLIBCVER}/glibc-${GLIBCVER}-headers.tar.xz  glibc-${GLIBCVER}/glibc-${GLIBCVER}-static.tar.xz \
              kernel-headers.tar.xz /dist/pkg/java-jar.tar.xz;do
  if [ -f ${devpkg} ];then
    tar -C ${STATICROOT} -xJf ${devpkg};
  fi;
done;

for sysdir in proc sys dev root tmp usr/src dist etc/xml;do
  mkdir -p ${STATICROOT}/${sysdir}
done;

cp /etc/passwd /etc/group ${STATICROOT}/etc
if [ -x /usr/bin/xmlcatalog ];then
  xmlcatalog --noout --create ${STATICROOT}/etc/xml/docbook.xml
  xmlcatalog --noout --create ${STATICROOT}/etc/xml/docbook-xsl.xml
  xmlcatalog --noout --create ${STATICROOT}/etc/xml/catalog.xml
  xmlcatalog --noout --add nextCatalog "file:///etc/xml/docbook.xml" "" ${STATICROOT}/etc/xml/catalog.xml
  xmlcatalog --noout --add nextCatalog "file:///etc/xml/docbook-xsl.xml" "" ${STATICROOT}/etc/xml/catalog.xml
fi;

if [ -e ${STATICROOT}.sqfs ];then
  rm ${STATICROOT}.sqfs
fi;
mksquashfs ${STATICROOT}/* ${STATICROOT}.sqfs -comp xz
