#!/bin/bash

if [ "${1}" ];then
  DARCH=${1};
 else
  DARCH=$( uname -m )
  case ${DARCH} in
    arm*)DARCH=arm;;
  esac;
fi;

ROOT=/dist/root/${DARCH}-static

for bind in dev proc sys usr/src/linux;do
  if [ ! -d ${ROOT}/${bind} ];then
    mkdir -p ${ROOT}/${bind}
  fi
  mount --bind /${bind} ${ROOT}/${bind}
done;

if [ -d ${ROOT}/proc/sys/fs/binfmt_misc ];then
  mount --bind /proc/sys/fs/binfmt_misc ${ROOT}/proc/sys/fs/binfmt_misc
fi;
