#!/bin/bash

if [ "${1}" ];then
  DARCH=${1};
 else
  DARCH=$( uname -m )
fi;

ROOT=/dist/root/${DARCH}-static

for bind in dev proc sys proc/sys/fs/binfmt_misc usr/src/linux;do
  if [ ! -d ${ROOT}/${bind} ];then
    mkdir -p ${ROOT}/${bind}
  fi
  mount --bind /${bind} ${ROOT}/${bind}
done;
