#!/bin/bash

eval `cat /dist/def/${2}`

if [ "${ALIAS}" ];then
  PNAME=${ALIAS}
  PROJECT=${ALIAS}${VERSEP}${VERSION}
 else
  PNAME=${2}
  PROJECT=${2}${VERSEP}${VERSION}
fi;

cd /usr/src/${PNAME}/${PROJECT}

if [ ${CFGPTH} ];then
  cd ${CFGPTH}
fi;

if [ "${BUILDDIR}" != "0" ];then
  cd build-${1}
fi;

make DESTDIR=/dist/${1}/${2}${VERSEP}${VERSION} all install || exit 255
rsync -avP /dist/${1}/${2}${VERSEP}${VERSION}/ /build/${1}/

if [ -e /dist/status/${1}/fail/${2} ];then
  rm /dist/status/${1}/fail/${2}
fi;

touch /dist/status/${1}/done/${2}
