#!/bin/bash

if [ "${1}" ];then
  DARCH=${1};
 else
  DARCH=$( uname -m )
fi;

ROOT=/dist/root/${DARCH}-static

for bind in dev proc sys proc/sys/fs/binfmt_misc usr/src/linux;do
  umount ${ROOT}/${bind}
done;
