#!/bin/bash

if [ "${1}" ];then
  ROOT=${1}
 else
  DARCH=$( uname -m )
  case ${DARCH} in
    arm*)DARCH=arm;;
    aarch)DARCH=arm64;;
    ppc)DARCH=powerpc;;
    ppc64)DARCH=powerpc64;;
  esac;
  ROOT=/dist/root/${DARCH}-static
fi;

for bind in dev/pts dev proc/sys/fs/binfmt_misc proc sys usr/src/linux;do
  if [ -d ${ROOT}/${bind} ];then
    umount ${ROOT}/${bind} >/dev/null 2>&1
  fi;
done;
