#!/bin/bash

PKG=$( basename `pwd` )
NARCH=i686

if (( $# < 1 ));then
  echo "Requires arg $0 [clean] <arm|x86_64|i686> ....."
  exit -1
fi;

ARG1=${1}
shift

if [ "${ARG1}" == "clean" ];then
  ARCH=${1}
  shift

  if [ -d build-${ARCH} ];then
    rm -rf build-${ARCH}
  fi;

  if [ -d /dist/${ARCH}/${PKG} ];then
    rm -rf /dist/${ARCH}/${PKG}
  fi;
  if [ -e Makefile ];then
    make clean
  fi;
 else
  ARCH=${ARG1}
fi;

if [ "${ARCH}" == "arm" ];then
  HOST=${ARCH}-embed-linux-gnueabi
 else
  HOST=${ARCH}-pc-linux-gnu
fi;

export CFLAGS="-I/dist/${ARCH}/include -I/dist/${ARCH}/usr/include"
export CPPFLAGS=${CFLAGS}
export LDFLAGS="-L/dist/${ARCH}/lib64 -L/dist/${ARCH}/usr/lib64 -L/dist/${ARCH}/lib -L/dist/${ARCH}/usr/lib"
export FORCE_UNSAFE_CONFIGURE=1

./configure --prefix=/usr --sysconfdir=/etc --mandir=/usr/share/man --localstatedir=/var --host=${HOST} "$@"

export DIST_ROOT=/dist/${ARCH}/${PKG}
if [ ! -d ${DIST_ROOT} ];then
  mkdir ${DIST_ROOT}
fi;
make DESTDIR=${DIST_ROOT} 
make DESTDIR=${DIST_ROOT} install
make DESTDIR=${DIST_ROOT} install-lib
if [ "${ARCH}" == "${NARCH}" ];then
  make install
fi;

rsync -avP /dist/${ARCH}/${PKG}/ /build/${ARCH}/
